### ISSUE TITLE
Ubuntu 14.10 x64 compiler error

### ISSUE THREAD

**Issue by JorritPosthuma** [EyalAr/lwip#120]
I tried using it on a clean image with only the following commands executed:

```bash
sudo apt-get update
sudo apt-get install build-essential
curl https://install.meteor.com/ | sh
```

Running it then exits with the following error
```
../src/lib/zlib/gzlib.c: In function ‘gz_open’:
../src/lib/zlib/gzlib.c:256:9: warning: implicit declaration of function ‘lseek’
[-Wimplicit-function-declaration]
state->start = LSEEK(state->fd, 0, SEEK_CUR);
^
../src/lib/zlib/gzread.c: In function ‘gz_load’:
../src/lib/zlib/gzread.c:30:9: warning: implicit declaration of function ‘read’
[-Wimplicit-function-declaration]
ret = read(state->fd, buf + *have, len - *have);
^
../src/lib/zlib/gzread.c: In function ‘gzclose_r’:
../src/lib/zlib/gzread.c:591:5: warning: implicit declaration of function ‘close’
[-Wimplicit-function-declaration]
ret = close(state->fd);
^
../src/lib/gif/dgif_lib.c: In function ‘DGifOpenFileHandle’:
../src/lib/gif/dgif_lib.c:32:64: warning: signed and unsigned type in conditional expression [-Wsign-compare]
((GifFilePrivateType*)_gif->Private)->Read(_gif,_buf,_len) :
\
^
../src/lib/gif/dgif_lib.c:116:9: note: in expansion of macro ‘READ’
if (READ(GifFile, (unsigned char *)Buf, GIF_STAMP_LEN) != GIF_STAMP_LEN) {
^
../src/lib/gif/dgif_lib.c: In function ‘DGifOpen’:
../src/lib/gif/dgif_lib.c:32:64: warning: signed and unsigned type in conditional expression [-Wsign-compare]
((GifFilePrivateType*)_gif->Private)->Read(_gif,_buf,_len) :
\
^
../src/lib/gif/dgif_lib.c:191:9: note: in expansion of macro ‘READ’
if (READ(GifFile, (unsigned char *)Buf, GIF_STAMP_LEN) != GIF_STAMP_LEN) {
^
../src/lib/gif/dgif_lib.c: In function ‘DGifGetScreenDesc’:
../src/lib/gif/dgif_lib.c:32:64: warning: signed and unsigned type in conditional expression [-Wsign-compare]
((GifFilePrivateType*)_gif->Private)->Read(_gif,_buf,_len) :
\
^
../src/lib/gif/dgif_lib.c:247:9: note: in expansion of macro ‘READ’
if (READ(GifFile, Buf, 3) != 3) {
^
../src/lib/gif/dgif_lib.c:32:64: warning: signed and unsigned type in conditional expression [-Wsign-compare]
((GifFilePrivateType*)_gif->Private)->Read(_gif,_buf,_len) :
\
^
../src/lib/gif/dgif_lib.c:270:17: note: in expansion of macro ‘READ’
if (READ(GifFile, Buf, 3) != 3) {
^
../src/lib/gif/dgif_lib.c: In function ‘DGifGetRecordType’:
../src/lib/gif/dgif_lib.c:32:64: warning: signed and unsigned type in conditional expression [-Wsign-compare]
((GifFilePrivateType*)_gif->Private)->Read(_gif,_buf,_len) :
\
^
../src/lib/gif/dgif_lib.c:302:9: note: in expansion of macro ‘READ’
if (READ(GifFile, &Buf, 1) != 1) {
^
../src/lib/gif/dgif_lib.c: In function ‘DGifGetImageDesc’:
../src/lib/gif/dgif_lib.c:32:64: warning: signed and unsigned type in conditional expression [-Wsign-compare]
((GifFilePrivateType*)_gif->Private)->Read(_gif,_buf,_len) :
\
^
../src/lib/gif/dgif_lib.c:349:9: note: in expansion of macro ‘READ’
if (READ(GifFile, Buf, 1) != 1) {
^
../src/lib/gif/dgif_lib.c:374:23: warning: comparison between signed and unsigned integer expressions
[-Wsign-compare]
for (i = 0; i < GifFile->Image.ColorMap->ColorCount; i++) {
^
../src/lib/gif/dgif_lib.c:32:64: warning: signed and unsigned type in conditional expression [-Wsign-compare]
((GifFilePrivateType*)_gif->Private)->Read(_gif,_buf,_len) :
\
^
../src/lib/gif/dgif_lib.c:375:17: note: in expansion of macro ‘READ’
if (READ(GifFile, Buf, 3) != 3) {
^
../src/lib/gif/dgif_lib.c: In function ‘DGifGetExtension’:
../src/lib/gif/dgif_lib.c:32:64: warning: signed and unsigned type in conditional expression [-Wsign-compare]
((GifFilePrivateType*)_gif->Private)->Read(_gif,_buf,_len) :
\
^
../src/lib/gif/dgif_lib.c:522:9: note: in expansion of macro ‘READ’
if (READ(GifFile, &Buf, 1) != 1) {
^
../src/lib/gif/dgif_lib.c: In function ‘DGifGetExtensionNext’:
../src/lib/gif/dgif_lib.c:32:64: warning: signed and unsigned type in conditional expression [-Wsign-compare]
((GifFilePrivateType*)_gif->Private)->Read(_gif,_buf,_len) :
\
^
../src/lib/gif/dgif_lib.c:542:9: note: in expansion of macro ‘READ’
if (READ(GifFile, &Buf, 1) != 1) {
^
../src/lib/gif/dgif_lib.c:32:64: warning: signed and unsigned type in conditional expression [-Wsign-compare]
((GifFilePrivateType*)_gif->Private)->Read(_gif,_buf,_len) :
\
^
../src/lib/gif/dgif_lib.c:550:13: note: in expansion of macro ‘READ’
if (READ(GifFile, &((*Extension)[1]), Buf) != Buf) {
^
../src/lib/gif/dgif_lib.c: In function ‘DGifGetWord’:
../src/lib/gif/dgif_lib.c:32:64: warning: signed and unsigned type in conditional expression [-Wsign-compare]
((GifFilePrivateType*)_gif->Private)->Read(_gif,_buf,_len) :
\
^
../src/lib/gif/dgif_lib.c:671:9: note: in expansion of macro ‘READ’
if (READ(GifFile, c, 2) != 2) {
^
../src/lib/gif/dgif_lib.c: In function ‘DGifGetCodeNext’:
../src/lib/gif/dgif_lib.c:32:64: warning: signed and unsigned type in conditional expression [-Wsign-compare]
((GifFilePrivateType*)_gif->Private)->Read(_gif,_buf,_len) :
\
^
../src/lib/gif/dgif_lib.c:715:9: note: in expansion of macro ‘READ’
if (READ(GifFile, &Buf, 1) != 1) {
^
../src/lib/gif/dgif_lib.c:32:64: warning: signed and unsigned type in conditional expression [-Wsign-compare]
((GifFilePrivateType*)_gif->Private)->Read(_gif,_buf,_len) :
\
^
../src/lib/gif/dgif_lib.c:725:13: note: in expansion of macro ‘READ’
if (READ(GifFile, &((*CodeBlock)[1]), Buf) != Buf) {
^
../src/lib/gif/dgif_lib.c: In function ‘DGifSetupDecompress’:
../src/lib/gif/dgif_lib.c:32:64: warning: signed and unsigned type in conditional expression [-Wsign-compare]
((GifFilePrivateType*)_gif->Private)->Read(_gif,_buf,_len) :
\
^
../src/lib/gif/dgif_lib.c:749:9: note: in expansion of macro ‘READ’
if (READ(GifFile, &CodeSize, 1) < 1) {    /* Read Code size from file. */
^
../src/lib/gif/dgif_lib.c: In function ‘DGifBufferedInput’:
../src/lib/gif/dgif_lib.c:32:64: warning: signed and unsigned type in conditional expression [-Wsign-compare]
((GifFilePrivateType*)_gif->Private)->Read(_gif,_buf,_len) :
\
^
../src/lib/gif/dgif_lib.c:1024:13: note: in expansion of macro ‘READ’
if (READ(GifFile, Buf, 1) != 1) {
^
../src/lib/gif/dgif_lib.c:32:64: warning: signed and unsigned type in conditional expression [-Wsign-compare]
((GifFilePrivateType*)_gif->Private)->Read(_gif,_buf,_len) :
\
^
../src/lib/gif/dgif_lib.c:1036:13: note: in expansion of macro ‘READ’
if (READ(GifFile, &Buf[1], Buf[0]) != Buf[0]) {
^
../src/encoder/png_worker.cpp: In member function ‘virtual void EncodeToPngBufferWorker::Execute()’:
../src/encoder/png_worker.cpp:24:9: warning: variable ‘n_chan’ might be clobbered by ‘longjmp’ or ‘vfork’
[-Wclobbered]
int n_chan = _trans ? RGBA_N_CHANNELS : RGB_N_CHANNELS;
^
../src/encoder/png_worker.cpp:27:9: warning: variable ‘compLevel’ might be clobbered by ‘longjmp’ or ‘vfork’
[-Wclobbered]
int compLevel;
^
../src/lib/png/pngwutil.c: In function ‘png_check_keyword’:
../src/lib/png/pngwutil.c:682:20: warning: unused variable ‘orig_key’ [-Wunused-variable]
png_const_charp orig_key = key;
^
../src/lib/zlib/gzlib.c: In function ‘gz_open’:
../src/lib/zlib/gzlib.c:256:9: warning: implicit declaration of function ‘lseek’
[-Wimplicit-function-declaration]
state->start = LSEEK(state->fd, 0, SEEK_CUR);
^
../src/lib/zlib/gzwrite.c: In function ‘gz_comp’:
../src/lib/zlib/gzwrite.c:84:9: warning: implicit declaration of function ‘write’
[-Wimplicit-function-declaration]
got = write(state->fd, strm->next_in, strm->avail_in);
^
../src/lib/zlib/gzwrite.c: In function ‘gzclose_w’:
../src/lib/zlib/gzwrite.c:573:5: warning: implicit declaration of function ‘close’
[-Wimplicit-function-declaration]
if (close(state->fd) == -1)
^
../src/lib/gif/egif_lib.c: In function ‘EGifPutScreenDesc’:
../src/lib/gif/egif_lib.c:285:38: warning: comparison between signed and unsigned integer expressions
[-Wsign-compare]
strlen(write_version)) != strlen(write_version)) {
^
../src/lib/gif/egif_lib.c: In function ‘EGifPutCodeNext’:
../src/lib/gif/egif_lib.c:735:16: warning: comparison between signed and unsigned integer expressions
[-Wsign-compare]
!= (unsigned)(CodeBlock[0] + 1)) {
^
../src/lib/gif/egif_lib.c: In function ‘EGifBufferedOutput’:
../src/lib/gif/egif_lib.c:1019:56: warning: comparison between signed and unsigned integer expressions
[-Wsign-compare]
&& InternalWrite(GifFile, Buf, Buf[0] + 1) != (unsigned)(Buf[0] + 1))
{
^
../src/lib/gif/egif_lib.c:1032:57: warning: comparison between signed and unsigned integer expressions
[-Wsign-compare]
if (InternalWrite(GifFile, Buf, Buf[0] + 1) != (unsigned)(Buf[0] + 1))
{
^
../src/lib/gif/quantize.c: In function ‘GifQuantizeBuffer’:
../src/lib/gif/quantize.c:132:25: warning: comparison between signed and unsigned integer expressions
[-Wsign-compare]
if (NewColorMapSize < *ColorMapSize) {
^
../src/lib/gif/quantize.c:141:19: warning: comparison between signed and unsigned integer expressions
[-Wsign-compare]
for (i = 0; i < NewColorMapSize; i++) {
^
g++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-4.9/README.Bugs> for instructions.
make: *** [Release/obj.target/lwip_image/src/image/image.o] Error 4
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit
(/root/.meteor/packages/meteor-tool/.1.0.41.yumiah++os.linux.x86_64+web.browser+web.cordova/meteor-tool-os.linux.x86_64/dev_bundle/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:810:12)
gyp ERR! System Linux 3.16.0-28-generic
gyp ERR! command "node"
"/root/.meteor/packages/meteor-tool/.1.0.41.yumiah++os.linux.x86_64+web.browser+web.cordova/meteor-tool-os.linux.x86_64/dev_bundle/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js"
"rebuild"
gyp ERR! cwd /root/soundsync/packages/npm-container/.npm/package-new-ik6zi1/node_modules/lwip
gyp ERR! node -v v0.10.33
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok 
```

**Comment by JorritPosthuma** [comment]
Sorry! It appeared to be a low memory problem (DigitalOcean $5 droplet problem), fixed it by creating a swap.
