### ISSUE TITLE
LWIP crashes after a few simple requests

### ISSUE THREAD

**Issue by timdonovanuk** [EyalAr/lwip#133]
I am using node v0.12.0, express and multer to handle POST'ed images and then using LWIP to process them. Node crashes after one or two requests (i.e. it will process and return at least image fine, but frequently crashes on the 2nd or 3rd request). I have simplified the code here, to use a static file, but even this code crashes:

    app.post('/lwip', function(req, res, next) {

    lwip.open('test.jpg', function(err, image) {
        var batch = image.batch();
        batch.blur(5).writeFile('test.jpg', function(err) {
            if (!err) {
                res.setHeader("content-type", "image/jpeg");
                fs.createReadStream(req.files.image.path).pipe(res);
            }
        });
    });

Here is the debug log:

````
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@2.5.1
3 info using node@v0.12.0
4 verbose node symlink C:\Program Files\nodejs\\node.exe
5 verbose run-script [ 'prestart', 'start', 'poststart' ]
6 info prestart LWIP-server@0.0.1
7 info start LWIP-server@0.0.1
8 verbose unsafe-perm in lifecycle true
9 info LWIP-server@0.0.1 Failed to exec start script
10 verbose stack Error: LWIP-server@0.0.1 start: `node ./index.js`
10 verbose stack Exit status 3221226356
10 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:213:16)
10 verbose stack     at EventEmitter.emit (events.js:110:17)
10 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:14:12)
10 verbose stack     at ChildProcess.emit (events.js:110:17)
10 verbose stack     at maybeClose (child_process.js:1008:16)
10 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1080:5)
11 verbose pkgid LWIP-server@0.0.1
12 verbose cwd C:\Node.js\lwip_express_server
13 error Windows_NT 6.1.7601
14 error argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
15 error node v0.12.0
16 error npm  v2.5.1
17 error code ELIFECYCLE
18 error LWIP-server@0.0.1 start: `node ./index.js`
18 error Exit status 3221226356
19 error Failed at the LWIP-server@0.0.1 start script 'node ./index.js'.
19 error This is most likely a problem with the LWIP-server package,
19 error not with npm itself.
19 error Tell the author that this fails on your system:
19 error     node ./index.js
19 error You can get their info via:
19 error     npm owner ls LWIP-server
19 error There is likely additional logging output above.
20 verbose exit [ 1, true ]
````
Please let me know if you need anymore info. Thanks.

**Comment by eNepper** [comment]
I'm experience something similar on linux. (Ubuntu 14.04, Node v0.10.25, lwip 0.0.8)
After 2 or 3 request node crashes with a "Process finished with exit code 139"
