### ISSUE TITLE
Can't install lwip on Mac OSX 10.10.3:  "Completion callback never invoked!"

### ISSUE THREAD

**Issue by jordan112** [EyalAr/lwip#151]
I can run everything else fine such as grunt, sass, ruby.  

I went through the steps to ensure I installed node-gyp

    npm install node-gyp

> I do have python, make and gcc installed fine as far as I can tell

I just can't get past this issue. 

```
npm install lwip
\
> lwip@0.0.6 install /Users/******/Documents/repos/*******/node_modules/lwip
> node-gyp rebuild

gyp ERR! Completion callback never invoked!
gyp ERR! System Darwin 14.3.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/******/Documents/repos/******/node_modules/lwip
gyp ERR! node -v v0.12.4
gyp ERR! node-gyp -v v1.0.3
gyp ERR! This is a bug in `node-gyp`.
gyp ERR! Try to update node-gyp and file an Issue if it does not help:
gyp ERR!     <https://github.com/TooTallNate/node-gyp/issues>
npm ERR! Darwin 14.3.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "lwip"
npm ERR! node v0.12.4
npm ERR! npm  v2.10.1
npm ERR! code ELIFECYCLE

npm ERR! lwip@0.0.6 install: `node-gyp rebuild`
npm ERR! Exit status 6
npm ERR!
npm ERR! Failed at the lwip@0.0.6 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the lwip package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls lwip
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/******/Documents/repos/******/npm-debug.log
```

> Note:  I added **** where my names was.

**Comment by jordan112** [comment]
Hmm...when I run this it fails.  Maybe not an issue with lwip.  

```
node-gyp rebuild
gyp info it worked if it ends with ok
gyp info using node-gyp@2.0.1
gyp info using node@0.12.4 | darwin | x64
gyp http GET http://nodejs.org/dist/v0.12.4/node-v0.12.4.tar.gz
gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: connect ETIMEDOUT
gyp ERR! stack     at exports._errnoException (util.js:746:11)
gyp ERR! stack     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1010:19)
gyp ERR! System Darwin 14.3.0
gyp ERR! command "node" "/usr/local/bin/node-gyp" "rebuild"
gyp ERR! cwd /Users/*****/Documents/repos/****
gyp ERR! node -v v0.12.4
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok
```

**Comment by jordan112** [comment]
For anyone that has this type of issue in the future, it's usually network related.  Try changing to a different network.  There might be firewalls.  Once I changed it finally worked.  Hope that helps.
