### ISSUE TITLE
Error: Module did not self-register.

### ISSUE THREAD

**Issue by kjda** [EyalAr/lwip#154]
I am trying to use this library. installation works fine. but when I run my app I get the following error.. I tried it using node 0.11.16, 0.12.2 and 0.12.4.. same problem!
```
module.js:522
  var nodePath = process.env['NODE_PATH'];
                        ^
Error: Module did not self-register.
    at Error (native)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at /.../node_modules/lwip/lib/Image.js:3:22
    at Object.<anonymous> (/.../node_modules/lwip/lib/Image.js:15:3)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at /.../node_modules/lwip/lib/ImagePrototypeInit.js:3:17
    at Object.<anonymous> (/.../node_modules/lwip/lib/ImagePrototypeInit.js:606:3)
    at Module._compile (module.js:460:26)
```

in some cases I get this error
```
module.js:355
  Module._extensions[extension](this, filename);
                               ^
Error: Module did not self-register.
    at Error (native)
    at Module.load (module.js:355:32)
..................
```
in node_modules/lwip/build/Release I have the following files:
```
.deps
.obj.target
linker.lock
lwip_decoder.node
lwip_encoder.node
lwip_image.node
```

**Comment by EyalAr** [comment]
Please try again with v0.0.7

**Comment by gmetais** [comment]
Hi @EyalAr and first of all, thank you for your great module!

I'm having a similar problem since I updated NodeJS from `v1.10.30` to `v1.12.4`. I updated lwip to v0.0.7 and it didn't fix the problem.

No problem on install, but when I launch my app:
```
dyld: lazy symbol binding failed: Symbol not found: _node_module_register
  Referenced from: /Users/gaelmetais/Documents/GitHub/YellowLabTools/node_modules/lwip/build/Release/lwip_image.node
  Expected in: dynamic lookup

dyld: Symbol not found: _node_module_register
  Referenced from: /Users/gaelmetais/Documents/GitHub/YellowLabTools/node_modules/lwip/build/Release/lwip_image.node
  Expected in: dynamic lookup
```

dyld is "the dynamic link editor" on Mac OSX.

**Comment by cyc115** [comment]
Hello , just want to say I have the same problem and I am using nwjs with
nw.js v0.12.2
io.js v1.2.0
Chromium 41.0.2272.76.

the error reported seems to be quite similar the the one above:
```
Error: Module did not self-register.
    at Error (native)
    at Module.load (module.js:346:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:356:17)
    at require (module.js:375:17)
    at D:\Users\michen\AppData\Local\Temp\nw11120_32007\node_modules\lwip\lib\Image.js:3:22
    at Object.<anonymous> (D:\Users\michen\AppData\Local\Temp\nw11120_32007\node_modules\lwip\lib\Image.js:15:3)
    at Module._compile (module.js:451:26)
    at Object.Module._extensions..js (module.js:469:10)
    at Module.load (module.js:346:32)
```

**Comment by DawsonG** [comment]
I've encountered the same issue using node 0.12.7 and lwip 0.0.7

**Comment by DawsonG** [comment]
I was able to fix the error by removing my node_modules directory and running npm i

**Comment by standup75** [comment]
Thank you! That solved this issue for me too. I think this should be marked as solved

**Comment by EyalAr** [comment]
This problem will occur if you have lwip installed with a specific version of node and then you update node without re-installing lwip.
Since lwip has a few native parts, they have to be compiled against a specific node version (hence the need to re-install lwip when updating node).

**To sum up:** Re-install lwip every time you update node.

**Comment by gmetais** [comment]
I'm still having the issue after updating node to either v0.12 or v4.2.

Deleting the node_modules folder and re-installing doesn't work :(

**Comment by gmetais** [comment]
Forget about it. I was misusing NVM, switching Node version to v4.2 on one of my console windows, and launching my app in another console, which was staying with the v0.10 Node version.

Sorry about that!

**Comment by miparnisari** [comment]
I'm having the same issue using Node 4.4.3 and Lwip 0.0.8 in a Vagrant virtual machine that runs Ubuntu 64-bit. The host machine is running Windows 10.

I ran `npm rebuild --no-bin-links` and got no errors but then...

```bash
vagrant@vagrant-ubuntu-trusty-64:/home/app/img$ node image_processor.js
module.js:434
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: Module did not self-register.
    at Error (native)
    at Object.Module._extensions..node (module.js:434:18)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at /home/vinti/picpic/node_modules/lwip/lib/Image.js:3:22
    at Object.<anonymous> (/home/vinti/picpic/node_modules/lwip/lib/Image.js:16:3)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
```

**Comment by miparnisari** [comment]
I downgraded Node to version 4.1.2 and it works now.
