### ISSUE TITLE
Error in loading LWIP in AWS instance. 

### ISSUE THREAD

**Issue by agarwalarpit** [EyalAr/lwip#155]
I'm running a piece of code on my local machine, which runs fine, however I just Archive the node_modules and the node-code for the server to run, but it gives me the following error - 

    at Module.load (module.js:356:32) at Function.Module._load (module.js:312:12) 
    at Module.require (module.js:364:17) at require (module.js:380:17) 
    at /var/task/node_modules/lwip/lib/Image.js:3:22 
    at Object.<anonymous> (/var/task/node_modules/lwip/lib/Image.js:15:3) 
    at Module._compile (module.js:456:26) 
    at Object.Module._extensions..js (module.js:474:10) 
    at Module.load (module.js:356:32) 
    at Function.Module._load (module.js:312:12)

Any idea what is causing this? 

@EyalAr Thanks for creating this repo, however what is the memory footprint for these functions?

**Comment by EyalAr** [comment]
Is that the full error?
