### ISSUE TITLE
Build Breaks with io.js 3.0 on Ubuntu 14.10

### ISSUE THREAD

**Issue by jacob-israel-turner** [EyalAr/lwip#169]
When initially trying to get this hosted on my server, iojs-v1.8.1 failed as well (though that may be unrelated).  I ended up using node 0.12.7.

Here are the logs for the failed build:

```
root@Israel:/code/temp/cs-server# npm install
npm WARN package.json cs-server@1.0.0 No repository field.
npm WARN optional dep failed, continuing fsevents@0.3.8
npm WARN cannot run in wd gifsicle@3.0.1 node lib/install.js (wd=/code/temp/cs-server/node_modules/imagemin/node_modules/imagemin-gifsicle/node_modules/gifsicle)

> optipng-bin@3.0.2 postinstall /code/temp/cs-server/node_modules/imagemin/node_modules/imagemin-optipng/node_modules/optipng-bin
> node lib/install.js

  ✔ optipng pre-build test passed successfully

> jpegtran-bin@3.0.4 postinstall /code/temp/cs-server/node_modules/imagemin/node_modules/imagemin-jpegtran/node_modules/jpegtran-bin
> node lib/install.js

  ✔ jpegtran pre-build test passed successfully
|
> lwip@0.0.7 install /code/temp/cs-server/node_modules/lwip
> node-gyp rebuild

make: Entering directory '/code/temp/cs-server/node_modules/lwip/build'
  CXX(target) Release/obj.target/lwip_decoder/src/decoder/init.o
In file included from ../src/decoder/decoder.h:13:0,
                 from ../src/decoder/init.cpp:1:
../node_modules/nan/nan.h:324:27: error: redefinition of ‘template<class T> v8::Local<T> Nan::imp::NanEnsureHandleOrPersistent(const v8::Local<T>&)’
   NAN_INLINE v8::Local<T> NanEnsureHandleOrPersistent(const v8::Local<T> &val) {
                           ^
../node_modules/nan/nan.h:319:17: note: ‘template<class T> v8::Handle<T> Nan::imp::NanEnsureHandleOrPersistent(v8::Handle<T>&)’ previously declared here
   v8::Handle<T> NanEnsureHandleOrPersistent(const v8::Handle<T> &val) {
                 ^
../node_modules/nan/nan.h:344:27: error: redefinition of ‘template<class T> v8::Local<T> Nan::imp::NanEnsureLocal(v8::Handle<T>&)’
   NAN_INLINE v8::Local<T> NanEnsureLocal(const v8::Handle<T> &val) {
                           ^
../node_modules/nan/nan.h:334:27: note: ‘template<class T> v8::Local<T> Nan::imp::NanEnsureLocal(const v8::Local<T>&)’ previously declared here
   NAN_INLINE v8::Local<T> NanEnsureLocal(const v8::Local<T> &val) {
                           ^
../node_modules/nan/nan.h:757:13: error: ‘node::smalloc’ has not been declared
     , node::smalloc::FreeCallback callback
             ^
../node_modules/nan/nan.h:757:35: error: expected ‘,’ or ‘...’ before ‘callback’
     , node::smalloc::FreeCallback callback
                                   ^
../node_modules/nan/nan.h: In function ‘v8::Local<v8::Object> NanNewBufferHandle(char*, size_t, int)’:
../node_modules/nan/nan.h:761:50: error: ‘callback’ was not declared in this scope
         v8::Isolate::GetCurrent(), data, length, callback, hint);
                                                  ^
../node_modules/nan/nan.h:761:60: error: ‘hint’ was not declared in this scope
         v8::Isolate::GetCurrent(), data, length, callback, hint);
                                                            ^
../node_modules/nan/nan.h: In function ‘v8::Local<v8::Object> NanNewBufferHandle(const char*, uint32_t)’:
../node_modules/nan/nan.h:768:67: error: call of overloaded ‘New(v8::Isolate*, const char*&, uint32_t&)’ is ambiguous
     return node::Buffer::New(v8::Isolate::GetCurrent(), data, size);
                                                                   ^
../node_modules/nan/nan.h:768:67: note: candidates are:
In file included from ../src/decoder/decoder.h:12:0,
                 from ../src/decoder/init.cpp:1:
/root/.node-gyp/3.0.0/include/node/node_buffer.h:35:40: note: v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate*, v8::Handle<v8::String>, node::encoding) <near match>
 NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                        ^
/root/.node-gyp/3.0.0/include/node/node_buffer.h:35:40: note:   no known conversion for argument 3 from ‘uint32_t {aka unsigned int}’ to ‘node::encoding’
/root/.node-gyp/3.0.0/include/node/node_buffer.h:47:40: note: v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate*, char*, size_t) <near match>
 NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                        ^
/root/.node-gyp/3.0.0/include/node/node_buffer.h:47:40: note:   no known conversion for argument 2 from ‘const char*’ to ‘char*’
In file included from ../src/decoder/decoder.h:13:0,
                 from ../src/decoder/init.cpp:1:
../node_modules/nan/nan.h: In function ‘v8::Local<v8::Object> NanNewBufferHandle(uint32_t)’:
../node_modules/nan/nan.h:772:61: error: could not convert ‘node::Buffer::New(v8::Isolate::GetCurrent(), ((size_t)size))’ from ‘v8::MaybeLocal<v8::Object>’ to ‘v8::Local<v8::Object>’
     return node::Buffer::New(v8::Isolate::GetCurrent(), size);
                                                             ^
../node_modules/nan/nan.h: In function ‘v8::Local<v8::Object> NanBufferUse(char*, uint32_t)’:
../node_modules/nan/nan.h:779:12: error: ‘Use’ is not a member of ‘node::Buffer’
     return node::Buffer::Use(v8::Isolate::GetCurrent(), data, size);
            ^
lwip_decoder.target.mk:163: recipe for target 'Release/obj.target/lwip_decoder/src/decoder/init.o' failed
make: *** [Release/obj.target/lwip_decoder/src/decoder/init.o] Error 1
make: Leaving directory '/code/temp/cs-server/node_modules/lwip/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/root/.nvm/versions/io.js/v3.0.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 3.16.0-28-generic
gyp ERR! command "/root/.nvm/versions/io.js/v3.0.0/bin/iojs" "/root/.nvm/versions/io.js/v3.0.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /code/temp/cs-server/node_modules/lwip
gyp ERR! node -v v3.0.0
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok
npm ERR! Linux 3.16.0-28-generic
npm ERR! argv "/root/.nvm/versions/io.js/v3.0.0/bin/iojs" "/root/.nvm/versions/io.js/v3.0.0/bin/npm" "install"
npm ERR! node v3.0.0
npm ERR! npm  v2.13.3
npm ERR! code ELIFECYCLE

npm ERR! lwip@0.0.7 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the lwip@0.0.7 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the lwip package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls lwip
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /code/temp/cs-server/npm-debug.log
```

I can provide any other logs that might help.

**Comment by jacob-israel-turner** [comment]
I just tested again, it looks like io.js v1.8.1 works fine.

**Comment by jacob-israel-turner** [comment]
It appears to break in 2.5.0 as well, though with a different log.

**Comment by laggingreflex** [comment]
Can confirm. It breaks in 2.3 as well. 
[installation log](http://pastebin.com/7B32czRR)
[npm-debug.log](http://pastebin.com/YgFUnHNL)

**Comment by jcsena** [comment]
I am testing lwip 0.0.7 in io.js 2.5.0 node-gyp 2.0.2 in mac ox el capitan beta 3 and sucessfully 

And i intall nvm and i testing iojs 3.x but catch error when is build

**Comment by unbornchikken** [comment]
io.js 3+ is totally different beast than anything was before. NAN 2.0 upgrade needs to be done in order to support io.js 3+, but that's gonna be a total rewrite of the native interfaces and anything involves NAN related code.

**Comment by EyalAr** [comment]
@unbornchikken Indeed, NAN 2 introduces support for io.js 3.
LWIP currently uses NAN 1.x. Upgrading to NAN 2.x will probably not be straightforward, which means io.js 3 support will be delayed.

**Comment by unbornchikken** [comment]
Well, I did node-ffi, ref, and I'm doing node-proxy, and I'm gonna do arrayfire_js nan 2 upgrade, so I have some experience on this topic. It takes about a hour to string replace, and ToLocalChecked everything. The tough part is when you have persistents, or making object templates, or forgot to use escapable scopes correctly. Or nan 2 forgot to implement something. :) Actually node-proxy upgrade is on hold because exactly of that.

When I finish the above, and there still won't be a PR there, then I'll help you with this.

**Comment by EyalAr** [comment]
@unbornchikken Awesome, thanks.

**Comment by OrKoN** [comment]
I have just tried node 4.0.0 and it looks like the same problem is occurring there too.

**Comment by craigbuckler** [comment]
I can confirm the lwip build breaks using Node 4.0 on Ubuntu Server 14.04.3.

**Comment by jcsena** [comment]
@craigbuckler  @OrKoN  this problem is because lwip use NAN 1.X and (node 4.0.0 - iojs 3.x) use NAN 2.0  and to solve this problem is necesary a migrations and I think this will take some time

**Comment by gblock0** [comment]
:+1: getting this error as well.

**Comment by EyalAr** [comment]
See #182
