### ISSUE TITLE
Windows Server 2012 R2 - Install Error

### ISSUE THREAD

**Issue by AndreasKnight** [EyalAr/lwip#178]
````
C:\Users\Administrator\Documents\GitHub\NodeBB [v0.8.x]> npm install lwip
-
> lwip@0.0.7 install C:\Users\Administrator\Documents\GitHub\NodeBB\node_modules\lwip
> node-gyp rebuild


C:\Users\Administrator\Documents\GitHub\NodeBB\node_modules\lwip>if not defined npm_config_node_gyp (node "C:\Program Fi
les\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuil
d )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  init.cpp
  util.cpp
C:\Users\Administrator\Documents\GitHub\NodeBB\node_modules\lwip\src\lib\gif\gif_lib.h(22): fatal error C1083: Cannot o
pen include file: 'stdbool.h': No such file or directory (..\src\decoder\init.cpp) [C:\Users\Administrator\Documents\Gi
tHub\NodeBB\node_modules\lwip\build\lwip_decoder.vcxproj]
C:\Users\Administrator\Documents\GitHub\NodeBB\node_modules\lwip\src\lib\gif\gif_lib.h(22): fatal error C1083: Cannot o
pen include file: 'stdbool.h': No such file or directory (..\src\decoder\util.cpp) [C:\Users\Administrator\Documents\Gi
tHub\NodeBB\node_modules\lwip\build\lwip_decoder.vcxproj]
  buffer_worker.cpp
  jpeg_decoder.cpp
C:\Users\Administrator\Documents\GitHub\NodeBB\node_modules\lwip\src\lib\gif\gif_lib.h(22): fatal error C1083: Cannot o
pen include file: 'stdbool.h': No such file or directory (..\src\decoder\jpeg_decoder.cpp) [C:\Users\Administrator\Docu
ments\GitHub\NodeBB\node_modules\lwip\build\lwip_decoder.vcxproj]
C:\Users\Administrator\Documents\GitHub\NodeBB\node_modules\lwip\src\lib\gif\gif_lib.h(22): fatal error C1083: Cannot o
pen include file: 'stdbool.h': No such file or directory (..\src\decoder\buffer_worker.cpp) [C:\Users\Administrator\Doc
uments\GitHub\NodeBB\node_modules\lwip\build\lwip_decoder.vcxproj]
  png_decoder.cpp
  gif_decoder.cpp
C:\Users\Administrator\Documents\GitHub\NodeBB\node_modules\lwip\src\lib\gif\gif_lib.h(22): fatal error C1083: Cannot o
pen include file: 'stdbool.h': No such file or directory (..\src\decoder\gif_decoder.cpp) [C:\Users\Administrator\Docum
ents\GitHub\NodeBB\node_modules\lwip\build\lwip_decoder.vcxproj]
C:\Users\Administrator\Documents\GitHub\NodeBB\node_modules\lwip\src\lib\gif\gif_lib.h(22): fatal error C1083: Cannot o
pen include file: 'stdbool.h': No such file or directory (..\src\decoder\png_decoder.cpp) [C:\Users\Administrator\Docum
ents\GitHub\NodeBB\node_modules\lwip\build\lwip_decoder.vcxproj]
  init.cpp
  jpeg_worker.cpp
C:\Users\Administrator\Documents\GitHub\NodeBB\node_modules\lwip\src\lib\gif\gif_lib.h(22): fatal error C1083: Cannot o
pen include file: 'stdbool.h': No such file or directory (..\src\encoder\init.cpp) [C:\Users\Administrator\Documents\Gi
tHub\NodeBB\node_modules\lwip\build\lwip_encoder.vcxproj]
  png_worker.cpp
C:\Users\Administrator\Documents\GitHub\NodeBB\node_modules\lwip\src\lib\gif\gif_lib.h(22): fatal error C1083: Cannot o
pen include file: 'stdbool.h': No such file or directory (..\src\encoder\jpeg_worker.cpp) [C:\Users\Administrator\Docum
ents\GitHub\NodeBB\node_modules\lwip\build\lwip_encoder.vcxproj]
  gif_worker.cpp
C:\Users\Administrator\Documents\GitHub\NodeBB\node_modules\lwip\src\lib\gif\gif_lib.h(22): fatal error C1083: Cannot o
pen include file: 'stdbool.h': No such file or directory (..\src\encoder\png_worker.cpp) [C:\Users\Administrator\Docume
nts\GitHub\NodeBB\node_modules\lwip\build\lwip_encoder.vcxproj]
C:\Users\Administrator\Documents\GitHub\NodeBB\node_modules\lwip\src\lib\gif\gif_lib.h(22): fatal error C1083: Cannot o
pen include file: 'stdbool.h': No such file or directory (..\src\encoder\gif_worker.cpp) [C:\Users\Administrator\Docume
nts\GitHub\NodeBB\node_modules\lwip\build\lwip_encoder.vcxproj]
  init.cpp
  image.cpp
..\src\image\image.cpp(34): warning C4267: 'argument' : conversion from 'size_t' to 'const unsigned int', possible loss
 of data [C:\Users\Administrator\Documents\GitHub\NodeBB\node_modules\lwip\build\lwip_image.vcxproj]
..\src\image\image.cpp(53): warning C4244: 'initializing' : conversion from 'double' to 'size_t', possible loss of data
 [C:\Users\Administrator\Documents\GitHub\NodeBB\node_modules\lwip\build\lwip_image.vcxproj]
..\src\image\image.cpp(54): warning C4244: 'initializing' : conversion from 'double' to 'size_t', possible loss of data
 [C:\Users\Administrator\Documents\GitHub\NodeBB\node_modules\lwip\build\lwip_image.vcxproj]
..\src\image\image.cpp(89): warning C4267: 'argument' : conversion from 'size_t' to 'const unsigned int', possible loss
 of data [C:\Users\Administrator\Documents\GitHub\NodeBB\node_modules\lwip\build\lwip_image.vcxproj]
..\src\image\image.cpp(90): warning C4267: 'argument' : conversion from 'size_t' to 'const unsigned int', possible loss
 of data [C:\Users\Administrator\Documents\GitHub\NodeBB\node_modules\lwip\build\lwip_image.vcxproj]
..\src\image\image.cpp(91): warning C4267: 'argument' : conversion from 'size_t' to 'const unsigned int', possible loss
 of data [C:\Users\Administrator\Documents\GitHub\NodeBB\node_modules\lwip\build\lwip_image.vcxproj]
..\src\image\image.cpp(92): warning C4267: 'argument' : conversion from 'size_t' to 'const unsigned int', possible loss
 of data [C:\Users\Administrator\Documents\GitHub\NodeBB\node_modules\lwip\build\lwip_image.vcxproj]
..\src\image\image.cpp(118): warning C4244: 'initializing' : conversion from 'int64_t' to 'int', possible loss of data
[C:\Users\Administrator\Documents\GitHub\NodeBB\node_modules\lwip\build\lwip_image.vcxproj]
  resize_worker.cpp
  rotate_worker.cpp
..\src\image\resize_worker.cpp(16): warning C4267: 'argument' : conversion from 'size_t' to 'const int', possible loss
of data [C:\Users\Administrator\Documents\GitHub\NodeBB\node_modules\lwip\build\lwip_image.vcxproj]
..\src\image\rotate_worker.cpp(23): warning C4267: 'argument' : conversion from 'size_t' to 'const unsigned int', possi
ble loss of data [C:\Users\Administrator\Documents\GitHub\NodeBB\node_modules\lwip\build\lwip_image.vcxproj]
..\src\image\rotate_worker.cpp(30): warning C4267: 'argument' : conversion from 'size_t' to 'const unsigned int', possi
ble loss of data [C:\Users\Administrator\Documents\GitHub\NodeBB\node_modules\lwip\build\lwip_image.vcxproj]
..\src\image\rotate_worker.cpp(34): warning C4267: 'argument' : conversion from 'size_t' to 'const unsigned int', possi
ble loss of data [C:\Users\Administrator\Documents\GitHub\NodeBB\node_modules\lwip\build\lwip_image.vcxproj]
  blur_worker.cpp
  crop_worker.cpp
  mirror_worker.cpp
..\src\image\crop_worker.cpp(17): warning C4267: 'argument' : conversion from 'size_t' to 'const int', possible loss of
 data [C:\Users\Administrator\Documents\GitHub\NodeBB\node_modules\lwip\build\lwip_image.vcxproj]
  pad_worker.cpp
  sharpen_worker.cpp
..\src\image\pad_worker.cpp(27): warning C4267: 'argument' : conversion from 'size_t' to 'const unsigned int', possible
 loss of data [C:\Users\Administrator\Documents\GitHub\NodeBB\node_modules\lwip\build\lwip_image.vcxproj]
..\src\image\pad_worker.cpp(35): warning C4267: 'argument' : conversion from 'size_t' to 'const unsigned int', possible
 loss of data [C:\Users\Administrator\Documents\GitHub\NodeBB\node_modules\lwip\build\lwip_image.vcxproj]
..\src\image\pad_worker.cpp(41): warning C4267: 'argument' : conversion from 'size_t' to 'const unsigned int', possible
 loss of data [C:\Users\Administrator\Documents\GitHub\NodeBB\node_modules\lwip\build\lwip_image.vcxproj]
..\src\image\pad_worker.cpp(47): warning C4267: 'argument' : conversion from 'size_t' to 'const unsigned int', possible
 loss of data [C:\Users\Administrator\Documents\GitHub\NodeBB\node_modules\lwip\build\lwip_image.vcxproj]
..\src\image\pad_worker.cpp(53): warning C4267: 'argument' : conversion from 'size_t' to 'const unsigned int', possible
 loss of data [C:\Users\Administrator\Documents\GitHub\NodeBB\node_modules\lwip\build\lwip_image.vcxproj]
..\src\image\pad_worker.cpp(62): warning C4267: 'argument' : conversion from 'size_t' to 'const unsigned int', possible
 loss of data [C:\Users\Administrator\Documents\GitHub\NodeBB\node_modules\lwip\build\lwip_image.vcxproj]
  hsla_worker.cpp
C:\Users\Administrator\Documents\GitHub\NodeBB\node_modules\lwip\src\lib\cimg\CImg.h(17069): warning C4244: '=' : conve
rsion from 'double' to 'float', possible loss of data (..\src\image\sharpen_worker.cpp) [C:\Users\Administrator\Documen
ts\GitHub\NodeBB\node_modules\lwip\build\lwip_image.vcxproj]
          C:\Users\Administrator\Documents\GitHub\NodeBB\node_modules\lwip\src\lib\cimg\CImg.h(16781) : see reference t
  o function template instantiation 'const cimg_library::CImg<T> &cimg_library::CImg<T>::SVD<float>(cimg_library::CImg<
  T> &,cimg_library::CImg<T> &,cimg_library::CImg<T> &,const bool,const unsigned int,const float) const' being compiled
          with
          [
              T=float
          ]
          C:\Users\Administrator\Documents\GitHub\NodeBB\node_modules\lwip\src\lib\cimg\CImg.h(16781) : see reference t
  o function template instantiation 'const cimg_library::CImg<T> &cimg_library::CImg<T>::SVD<float>(cimg_library::CImg<
  T> &,cimg_library::CImg<T> &,cimg_library::CImg<T> &,const bool,const unsigned int,const float) const' being compiled
          with
          [
              T=float
          ]
          C:\Users\Administrator\Documents\GitHub\NodeBB\node_modules\lwip\src\lib\cimg\CImg.h(25714) : see reference t
  o function template instantiation 'const cimg_library::CImg<T> &cimg_library::CImg<T>::symmetric_eigen<float>(cimg_li
  brary::CImg<T> &,cimg_library::CImg<T> &) const' being compiled
          with
          [
              T=float
          ]
          C:\Users\Administrator\Documents\GitHub\NodeBB\node_modules\lwip\src\lib\cimg\CImg.h(25714) : see reference t
  o function template instantiation 'const cimg_library::CImg<T> &cimg_library::CImg<T>::symmetric_eigen<float>(cimg_li
  brary::CImg<T> &,cimg_library::CImg<T> &) const' being compiled
          with
          [
              T=float
          ]
          C:\Users\Administrator\Documents\GitHub\NodeBB\node_modules\lwip\src\lib\cimg\CImg.h(25697) : while compiling
   class template member function 'cimg_library::CImg<T> &cimg_library::CImg<T>::sharpen(const float,const bool,const f
  loat,const float,const float)'
          with
          [
              T=unsigned char
          ]
          ..\src\image\sharpen_worker.cpp(14) : see reference to function template instantiation 'cimg_library::CImg<T>
   &cimg_library::CImg<T>::sharpen(const float,const bool,const float,const float,const float)' being compiled
          with
          [
              T=unsigned char
          ]
          C:\Users\Administrator\Documents\GitHub\NodeBB\node_modules\lwip\src\lib\cimg\CImg.h(47575) : see reference t
  o class template instantiation 'cimg_library::CImg<T>' being compiled
          with
          [
              T=unsigned char
          ]
C:\Users\Administrator\Documents\GitHub\NodeBB\node_modules\lwip\src\lib\cimg\CImg.h(17071): warning C4244: '=' : conve
rsion from 'double' to 'float', possible loss of data (..\src\image\sharpen_worker.cpp) [C:\Users\Administrator\Documen
ts\GitHub\NodeBB\node_modules\lwip\build\lwip_image.vcxproj]
C:\Users\Administrator\Documents\GitHub\NodeBB\node_modules\lwip\src\lib\cimg\CImg.h(17078): warning C4244: '=' : conve
rsion from 'double' to 'float', possible loss of data (..\src\image\sharpen_worker.cpp) [C:\Users\Administrator\Documen
ts\GitHub\NodeBB\node_modules\lwip\build\lwip_image.vcxproj]
C:\Users\Administrator\Documents\GitHub\NodeBB\node_modules\lwip\src\lib\cimg\CImg.h(17082): warning C4244: '=' : conve
rsion from 'double' to 'float', possible loss of data (..\src\image\sharpen_worker.cpp) [C:\Users\Administrator\Documen
ts\GitHub\NodeBB\node_modules\lwip\build\lwip_image.vcxproj]
  opacify_worker.cpp
..\src\image\hsla_worker.cpp(31): warning C4244: '*=' : conversion from 'double' to 'float', possible loss of data [C:\
Users\Administrator\Documents\GitHub\NodeBB\node_modules\lwip\build\lwip_image.vcxproj]
..\src\image\hsla_worker.cpp(37): warning C4244: '*=' : conversion from 'double' to 'float', possible loss of data [C:\
Users\Administrator\Documents\GitHub\NodeBB\node_modules\lwip\build\lwip_image.vcxproj]
..\src\image\hsla_worker.cpp(43): warning C4244: '*=' : conversion from 'double' to 'float', possible loss of data [C:\
Users\Administrator\Documents\GitHub\NodeBB\node_modules\lwip\build\lwip_image.vcxproj]
..\src\image\hsla_worker.cpp(70): warning C4244: 'initializing' : conversion from 'double' to 'float', possible loss of
 data [C:\Users\Administrator\Documents\GitHub\NodeBB\node_modules\lwip\build\lwip_image.vcxproj]
..\src\image\hsla_worker.cpp(71): warning C4244: 'initializing' : conversion from 'double' to 'float', possible loss of
 data [C:\Users\Administrator\Documents\GitHub\NodeBB\node_modules\lwip\build\lwip_image.vcxproj]
..\src\image\hsla_worker.cpp(72): warning C4244: 'initializing' : conversion from 'double' to 'float', possible loss of
 data [C:\Users\Administrator\Documents\GitHub\NodeBB\node_modules\lwip\build\lwip_image.vcxproj]
  paste_worker.cpp
  setpixel_worker.cpp
..\src\image\paste_worker.cpp(21): warning C4267: 'argument' : conversion from 'size_t' to 'const unsigned int', possib
le loss of data [C:\Users\Administrator\Documents\GitHub\NodeBB\node_modules\lwip\build\lwip_image.vcxproj]
..\src\image\paste_worker.cpp(24): warning C4267: 'argument' : conversion from 'size_t' to 'const unsigned int', possib
le loss of data [C:\Users\Administrator\Documents\GitHub\NodeBB\node_modules\lwip\build\lwip_image.vcxproj]
..\src\image\paste_worker.cpp(24): warning C4244: 'initializing' : conversion from 'double' to 'float', possible loss o
f data [C:\Users\Administrator\Documents\GitHub\NodeBB\node_modules\lwip\build\lwip_image.vcxproj]
..\src\image\paste_worker.cpp(25): warning C4267: 'argument' : conversion from 'size_t' to 'const unsigned int', possib
le loss of data [C:\Users\Administrator\Documents\GitHub\NodeBB\node_modules\lwip\build\lwip_image.vcxproj]
..\src\image\paste_worker.cpp(25): warning C4244: 'initializing' : conversion from 'double' to 'float', possible loss o
f data [C:\Users\Administrator\Documents\GitHub\NodeBB\node_modules\lwip\build\lwip_image.vcxproj]
..\src\image\paste_worker.cpp(28): warning C4267: 'argument' : conversion from 'size_t' to 'const unsigned int', possib
le loss of data [C:\Users\Administrator\Documents\GitHub\NodeBB\node_modules\lwip\build\lwip_image.vcxproj]
..\src\image\paste_worker.cpp(29): warning C4267: 'argument' : conversion from 'size_t' to 'const unsigned int', possib
le loss of data [C:\Users\Administrator\Documents\GitHub\NodeBB\node_modules\lwip\build\lwip_image.vcxproj]
..\src\image\paste_worker.cpp(30): warning C4267: 'argument' : conversion from 'size_t' to 'const unsigned int', possib
le loss of data [C:\Users\Administrator\Documents\GitHub\NodeBB\node_modules\lwip\build\lwip_image.vcxproj]
..\src\image\paste_worker.cpp(31): warning C4267: 'argument' : conversion from 'size_t' to 'const unsigned int', possib
le loss of data [C:\Users\Administrator\Documents\GitHub\NodeBB\node_modules\lwip\build\lwip_image.vcxproj]
..\src\image\paste_worker.cpp(32): warning C4267: 'argument' : conversion from 'size_t' to 'const unsigned int', possib
le loss of data [C:\Users\Administrator\Documents\GitHub\NodeBB\node_modules\lwip\build\lwip_image.vcxproj]
..\src\image\paste_worker.cpp(33): warning C4267: 'argument' : conversion from 'size_t' to 'const unsigned int', possib
le loss of data [C:\Users\Administrator\Documents\GitHub\NodeBB\node_modules\lwip\build\lwip_image.vcxproj]
..\src\image\paste_worker.cpp(40): warning C4267: 'argument' : conversion from 'size_t' to 'const unsigned int', possib
le loss of data [C:\Users\Administrator\Documents\GitHub\NodeBB\node_modules\lwip\build\lwip_image.vcxproj]
..\src\image\setpixel_worker.cpp(19): warning C4267: 'argument' : conversion from 'size_t' to 'const unsigned int', pos
sible loss of data [C:\Users\Administrator\Documents\GitHub\NodeBB\node_modules\lwip\build\lwip_image.vcxproj]
     Creating library C:\Users\Administrator\Documents\GitHub\NodeBB\node_modules\lwip\build\Release\lwip_image.lib and
   object C:\Users\Administrator\Documents\GitHub\NodeBB\node_modules\lwip\build\Release\lwip_image.exp
  Generating code
  Finished generating code
  lwip_image.vcxproj -> C:\Users\Administrator\Documents\GitHub\NodeBB\node_modules\lwip\build\Release\\lwip_image.node
gyp ERR! build error
gyp ERR! stack Error: `msbuild` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:2
69:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "node" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuil
d"
gyp ERR! cwd C:\Users\Administrator\Documents\GitHub\NodeBB\node_modules\lwip
gyp ERR! node -v v0.12.7
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "i
nstall" "lwip"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE

npm ERR! lwip@0.0.7 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the lwip@0.0.7 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the lwip package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls lwip
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Administrator\Documents\GitHub\NodeBB\npm-debug.log
````

Help please.

**Comment by oliversalzburg** [comment]
Same issue on Windows 10. I feel like I've been here before...

**Comment by EyalAr** [comment]
Seems to be a problem with your system's configuration ([fatal error C1083](https://msdn.microsoft.com/en-us/library/et4zwx34.aspx?f=255&MSPPError=-2147217396)).

Which version of VS are you using?
