### ISSUE TITLE
Make sure the module compiles and works on major platforms

### ISSUE THREAD

**Issue by EyalAr** [EyalAr/lwip#18]

**Comment by cbratschi** [comment]
Visual Studio 2013 Ultimate Update 4 fails on Windows 8.1:

  jpeg_decoder.cpp
...\node_modules\lwip\src\lib\gif\gif_lib.h(22): fatal error C1083: Cannot open include file: 'stdbool.h': No such file or directory [...\node_modules\lwip\build\lwip_decoder.vcxproj]

This is a C99 specific error. stdbool.h should be supported by VS 2013. Anyone else getting this error?

**Comment by frzsombor** [comment]
@cbratschi: 
I had exactly the same problem on Windows 7 x64, but after checking [node-gyp's install guide](https://github.com/TooTallNate/node-gyp/#installation), I saw that I'm missing Microsof Visual C++ 2012/13. I've installed 2013 Express and problem solved.
_Note to others: If you found this page searching for node-gyp errors, try to downgrade from NodeJS v0.12.0 to v0.10.x, it solved me an other problem with a package called [gaze](https://github.com/shama/gaze/issues/175) (required by css-sprite)._

**Comment by frzsombor** [comment]
I'm getting this error too, and can't find any solution
Windows 7 x64, VS 2013 Express Update 4
Please check the images below:
[image1](https://cloud.githubusercontent.com/assets/7306657/6425789/80e0c228-bf3b-11e4-8e63-7eda3f1caab8.png)
[image2](https://cloud.githubusercontent.com/assets/7306657/6425803/2e8ad8dc-bf3c-11e4-9509-7b2338369330.png)
[image3](https://cloud.githubusercontent.com/assets/7306657/6425804/396e9586-bf3c-11e4-8249-1f3e14779230.png)

**Comment by MyLittleRobo** [comment]
Same problem on Windows 8.1, Visual Studio 2013 Professional

**Comment by ddaeschler** [comment]
Just FYI for anyone having build issues on windows.

VS2012 is also missing stdbool.h, so I was able to get a build to complete under by making a small change to src/lib/gif/gif_lib.h.

Remove #include <stdbool.h>

replace it with:

#ifndef __cplusplus
typedef int bool;
#define true 1
#define false 0
#endif

I'm curious if this is still an issue with VS2015.

**Comment by cbratschi** [comment]
@ddaeschler at least it is still in VS 2013. Didn't try VS 2015 RC yet.

**Comment by toolness** [comment]
It seems odd that VS 2013 won't compile, since the dependency on C99/`bool` was documented in the description for #77 and @EyalAr even [mentioned](https://github.com/EyalAr/lwip/issues/18#issuecomment-68026633) that 0.0.6 (which has the same dependencies on `stdbool.h`) compiled on VS 2013. Microsoft's own [C99 library support in Visual Studio 2013](http://blogs.msdn.com/b/vcblog/archive/2013/07/19/c99-library-support-in-visual-studio-2013.aspx) blog post seems to corroborate this.

In any case, as a workaround--I'm still on VS 2010 and want it to be easy for others to easily build my project--I've just downgrated to lwip 0.5, as it has what I need and builds fine. That said, I'm looking forward to having pre-built binaries available for this excellent library!

**Comment by sasnfbi1234** [comment]
I am unable to install lwip on ubuntu 

gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/root/.nvm/v5.0.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 3.13.0-32-generic
gyp ERR! command "/root/.nvm/v5.0.0/bin/node" "/root/.nvm/v5.0.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /root/node_modules/lwip
gyp ERR! node -v v5.0.0
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
npm WARN ENOENT ENOENT: no such file or directory, open '/root/package.json'
npm WARN EPACKAGEJSON /root No description
npm WARN EPACKAGEJSON /root No repository field.
npm WARN EPACKAGEJSON /root No README data
npm WARN EPACKAGEJSON /root No license field.
npm ERR! Linux 3.13.0-32-generic
npm ERR! argv "/root/.nvm/v5.0.0/bin/node" "/root/.nvm/v5.0.0/bin/npm" "install" "lwip"
npm ERR! node v5.0.0
npm ERR! npm  v3.3.6
npm ERR! code ELIFECYCLE

npm ERR! lwip@0.0.8 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the lwip@0.0.8 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the lwip package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls lwip
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/npm-debug.log

**Comment by alt234** [comment]
@EyalAr would it be possible to get a check on Ubuntu 12.04 with gcc 4.8 and Node 5.x? This won't install there for us even after upgrading from gcc 4.6 to 4.8.1. It's the same thing on Debian 8. Perhaps it could be a thing with latest versions of V8? I've attached the stack trace for the error. It'd be great to be able to use this library. Thank you!

[stacktrace.txt](https://github.com/EyalAr/lwip/files/151593/stacktrace.txt)
