### ISSUE TITLE
v0.0.8 doesn't compile with Node 4 on windows 7 wit VS2012

### ISSUE THREAD

**Issue by Pomax** [EyalAr/lwip#196]
Trying to install `lwip` v0.0.8 using node 4.1.1 and npm 2.14.4 does not seem to work on Windows 7 with VS2012 as compilation platform. The result is the following (rather huge) pastebin: https://pastebin.mozilla.org/8849263

It seems like it's trying to compile using the Node 0.12 version of V8's headers, which are no longer applicable to the much more modern version of V8 that comes with Node 4...

**Comment by EyalAr** [comment]
[Notice that VS2013 or higher is required](https://github.com/EyalAr/lwip#installation)

**Comment by Pomax** [comment]
So noted - is there a way to tell node-gyp that? Because that's a pretty hardcore requirement.

**Comment by EyalAr** [comment]
Indeed that would be good. Let me check :)

**Comment by Pomax** [comment]
Running `npm install` with Visual Studio express 2013:
```
C:\Users\Mike\Documents\Git projects\collaborations\webmaker-suite\teach.webmaker.org>npm install lwip
\
> lwip@0.0.8 install C:\Users\Mike\Documents\Git projects\collaborations\webmaker-suite\teach.webmaker.org\node_modules\lwip
> node-gyp rebuild


C:\Users\Mike\Documents\Git projects\collaborations\webmaker-suite\teach.webmaker.org\node_modules\lwip>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modu
les\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.Cpp.Platform.targets(64,5): error MSB8020: The build tools for Visual Studio 2012 (Platform Toolset = 'v110') cannot be found. To build using the v110 bui
ld tools, please install Visual Studio 2012 build tools.  Alternatively, you may upgrade to the current Visual Studio tools by selecting the Project menu or right-click the solution, and then selecting "Upgrade Solution
...". [C:\Users\Mike\Documents\Git projects\collaborations\webmaker-suite\teach.webmaker.org\node_modules\lwip\build\lwip_decoder.vcxproj]
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.Cpp.Platform.targets(64,5): error MSB8020: The build tools for Visual Studio 2012 (Platform Toolset = 'v110') cannot be found. To build using the v110 bui
ld tools, please install Visual Studio 2012 build tools.  Alternatively, you may upgrade to the current Visual Studio tools by selecting the Project menu or right-click the solution, and then selecting "Upgrade Solution
...". [C:\Users\Mike\Documents\Git projects\collaborations\webmaker-suite\teach.webmaker.org\node_modules\lwip\build\lwip_encoder.vcxproj]
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.Cpp.Platform.targets(64,5): error MSB8020: The build tools for Visual Studio 2012 (Platform Toolset = 'v110') cannot be found. To build using the v110 bui
ld tools, please install Visual Studio 2012 build tools.  Alternatively, you may upgrade to the current Visual Studio tools by selecting the Project menu or right-click the solution, and then selecting "Upgrade Solution
...". [C:\Users\Mike\Documents\Git projects\collaborations\webmaker-suite\teach.webmaker.org\node_modules\lwip\build\lwip_image.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\12.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Mike\Documents\Git projects\collaborations\webmaker-suite\teach.webmaker.org\node_modules\lwip
gyp ERR! node -v v4.1.1
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "lwip"
npm ERR! node v4.1.1
npm ERR! npm  v2.14.4
npm ERR! code ELIFECYCLE

npm ERR! lwip@0.0.8 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the lwip@0.0.8 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the lwip package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls lwip
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Mike\Documents\Git projects\collaborations\webmaker-suite\teach.webmaker.org\npm-debug.log
```

**Comment by EyalAr** [comment]
> error MSB8020: The build tools for Visual Studio 2012 (Platform Toolset = 'v110') cannot be found.

Would indicate your system is still configured to use VS2012.

Try installing with the flag `–msvs_version=2013` or doing `npm config set msvs_version 2013 --global `

**Comment by Pomax** [comment]
Goddamnit visual studio, is there nothing you can just do right by running the un/installers =_= (I'm trying with 2013 instead of 2015 because the latter couldn't even finish installing. I gave up after seven mid-install system restarts). I'll try to scrub as much as I can, thanks.

**Comment by felixfbecker** [comment]
@Pomax It worked for me with Visual Studio 2015 on first try

**Comment by Pomax** [comment]
visual studio 2015 I'm sure has a better installer than 2015 community edition, but issues with 2015 is mostly an MS issue, so I'm willing to completely ignore that.

**Comment by felixfbecker** [comment]
I used VS 2015 Community Edition. All I checked in setup was install basic C++ tools.
