### ISSUE TITLE
Fails to install on OS X

### ISSUE THREAD

**Issue by leegee** [EyalAr/lwip#220]
[npm-debug.log.txt](https://github.com/EyalAr/lwip/files/61103/npm-debug.log.txt)

**Comment by hstonge** [comment]
Pretty much the same here on OS X 10.10.2 with  node 4.2.3 && npm 2.14.7

```
make: *** [Release/obj.target/lwip_decoder/src/decoder/init.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 14.1.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/hstonge/Documents/_WORK/argon18-site/node_modules/lwip
gyp ERR! node -v v4.2.3
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
npm ERR! Darwin 14.1.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--production"
npm ERR! node v4.2.3
npm ERR! npm  v2.14.7
npm ERR! code ELIFECYCLE
```

**Comment by AaronM04** [comment]
+1

**Comment by AaronM04** [comment]
I believe this happens with 0.0.7 but not 0.0.8.

**Comment by EyalAr** [comment]
@leegee, @hstonge 
Have you tried to follow the [OSX installation instructions](https://github.com/nodejs/node-gyp#installation)?

**Comment by hstonge** [comment]
I just retried installing, and somehow, version **0.0.8** is compiling fine now...
