### ISSUE TITLE
[TypeError: Cannot read property 'Kerberos' of undefined]

### ISSUE THREAD

**Issue by manV** [EyalAr/lwip#234]
When I install and run v0.0.8, this error gets thrown. here is the error stacktrace. I am using node-v4.2.1 on linux. Thanks.
```
[TypeError: Cannot read property 'Kerberos' of undefined]
module.js:460
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: Module did not self-register.
    at Error (native)
    at Object.Module._extensions..node (module.js:460:18)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at /home/ubuntu/panel/node_modules/lwip/lib/Image.js:3:22
    at Object.<anonymous> (/home/ubuntu/panel/node_modules/lwip/lib/Image.js:16:3)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at /home/ubuntu/panel/node_modules/lwip/lib/ImagePrototypeInit.js:3:17
    at Object.<anonymous> (/home/ubuntu/panel/node_modules/lwip/lib/ImagePrototypeInit.js:620:3)
```

**Comment by EyalAr** [comment]
lwip does not depend on kerberos. Could this be a problem with another module you're using?
Try to create a test app which uses lwip alone and see if you still have this error.

**Comment by manV** [comment]
Yes you are right, that kerberos line in the error was from some other module, I tried in a test project but still getting remaining part of the error. Thanks.
