### ISSUE TITLE
Build failed when pushing to digitalocean dokku stack

### ISSUE THREAD

**Issue by kaytrance** [EyalAr/lwip#241]
Node 4.2.1

Errors:

`  -----> Building dependencies
         Pruning any extraneous modules
         Installing node modules (package.json)
         
         > lwip@0.0.8 install /tmp/build/node_modules/lwip
         > node-gyp rebuild
         
         make: Entering directory `/tmp/build/node_modules/lwip/build'
         CXX(target) Release/obj.target/lwip_decoder/src/decoder/init.o
         g++: internal compiler error: Killed (program cc1plus)
         Please submit a full bug report,
         with preprocessed source if appropriate.
         See <file:///usr/share/doc/gcc-4.8/README.Bugs> for instructions.
         make: *** [Release/obj.target/lwip_decoder/src/decoder/init.o] Error 4
         make: Leaving directory `/tmp/build/node_modules/lwip/build'
         gyp ERR! build error
         gyp ERR! stack Error: `make` failed with exit code: 2
         gyp ERR! stack     at ChildProcess.onExit (/tmp/build/.heroku/node/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
         gyp ERR! stack     at emitTwo (events.js:87:13)
         gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
         gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
         gyp ERR! System Linux 3.13.0-71-generic
         gyp ERR! command "/tmp/build/.heroku/node/bin/node" "/tmp/build/.heroku/node/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
         gyp ERR! cwd /tmp/build/node_modules/lwip
         gyp ERR! node -v v4.2.1
         gyp ERR! node-gyp -v v3.0.3
         gyp ERR! not ok
         npm ERR! Linux 3.13.0-71-generic
         npm ERR! argv "/tmp/build/.heroku/node/bin/node" "/tmp/build/.heroku/node/bin/npm" "install" "--unsafe-perm" "--userconfig" "/tmp/build/.npmrc"
         npm ERR! node v4.2.1
         npm ERR! npm  v2.14.7
         npm ERR! code ELIFECYCLE
         
         npm ERR! lwip@0.0.8 install: `node-gyp rebuild`
         npm ERR! Exit status 1
         npm ERR!
         npm ERR! Failed at the lwip@0.0.8 install script 'node-gyp rebuild'.
         npm ERR! This is most likely a problem with the lwip package,
         npm ERR! not with npm itself.
         npm ERR! Tell the author that this fails on your system:
         npm ERR!     node-gyp rebuild
         npm ERR! You can get their info via:
         npm ERR!     npm owner ls lwip
         npm ERR! There is likely additional logging output above.
         
         npm ERR! Please include the following file with any support request:
         npm ERR!     /tmp/build/npm-debug.log
         
  -----> Build failed
         `

**Comment by kaytrance** [comment]
As is turned out I had to upgrade all ubuntu packages to make all work.
