### ISSUE TITLE
Cannot find module '../build/Release/lwip_image'

### ISSUE THREAD

**Issue by nvartolomei** [EyalAr/lwip#242]
Just installed lwip in another project and it throw this error, as I can understand the build fails.
Any ideas?

```
 → node index.js
module.js:341
    throw err;
    ^

Error: Cannot find module '../build/Release/lwip_image'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at /Users/nv/Projects/lwip-test/node_modules/lwip/lib/Image.js:3:22
    at Object.<anonymous> (/Users/nv/Projects/lwip-test/node_modules/lwip/lib/Image.js:16:3)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
```

node v5.6.0
npm 3.6.0
lwip 0.8.0

**Comment by nvartolomei** [comment]
Upgraded to latest version of node and npm, same thing.

**Comment by nvartolomei** [comment]
Found the issue root. node-gyp would do a Debug build if node is installed `--with-debug`. I think when loading lwip bindings we should check if debug build exists if release doesn't.

There is a package that does that: https://github.com/TooTallNate/node-bindings

**Comment by sadlerw** [comment]
any timeline for getting this fix in?  thanks, Will

**Comment by kalburgimanjunath** [comment]
any solution...
