### ISSUE TITLE
Not work on docker node official container

### ISSUE THREAD

**Issue by Andro999b** [EyalAr/lwip#260]
/usr/src/app/node_modules/bindings/bindings.js:83
        throw e
        ^

Error: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /usr/src/app/node_modules/lwip/build/Release/lwip_image.node)
    at Error (native)
    at Object.Module._extensions..node (module.js:568:18)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at bindings (/usr/src/app/node_modules/bindings/bindings.js:76:44)
    at /usr/src/app/node_modules/lwip/lib/Image.js:3:41
    at Object.<anonymous> (/usr/src/app/node_modules/lwip/lib/Image.js:16:3)

**Comment by cgarnier** [comment]
I got this issue too: 
PluggableError: lwip not found.

**Comment by ChristianRich** [comment]
+1
