### ISSUE TITLE
Crashing on Node 6

### ISSUE THREAD

**Issue by arackaf** [EyalAr/lwip#261]
Hi, I just upgraded to Node 6, and my app now crashes with the following trace, which appears to be related to lwip.

Thought I'd report it here.  I'll likely just downgrade back to Node 4 for now - thanks a ton for this wonderful library!

> Error: Module version mismatch. Expected 48, got 46.
    at Error (native)
    at Object.Module._extensions..node (module.js:568:18)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at bindings (C:\GIT\booklist\node_modules\bindings\bindings.js:76:44)
    at C:\GIT\booklist\node_modules\lwip\lib\Image.js:3:41
    at Object.<anonymous> (C:\GIT\booklist\node_modules\lwip\lib\Image.js:16:3)

**Comment by EyalAr** [comment]
Error: Module version mismatch. Expected 48, got 46.

You probably upgraded node without rebuilding the module against the new version. `npm rebuild` should solve it.

**Comment by arackaf** [comment]
I'm almost certain I re-installed everything under Node 6 -- would that not be equivalent?
