### ISSUE TITLE
Npm install does not work for Node v6.2.2

### ISSUE THREAD

**Issue by isaachinman** [EyalAr/lwip#262]
When I run `npm i lwip` with Node v6.2.2, I get the below error. Note this is not a system setup sort of problem, I have been using lwip via npm for months now, but as soon as I updated node, the package broke. If I downgrade to Node v5.x.x, everything works fine.

    lwip@0.0.8 install /path
    > node-gyp rebuild

    CXX(target) Release/obj.target/lwip_decoder/src/decoder/init.o
    In file included from ../src/decoder/init.cpp:1:
    In file included from ../src/decoder/decoder.h:13:
    ../../nan/nan.h:590:20: error: no type named 'GCEpilogueCallback' in 'v8::Isolate'
      v8::Isolate::GCEpilogueCallback callback
      ~~~~~~~~~~~~~^
    ../../nan/nan.h:596:20: error: no type named 'GCEpilogueCallback' in 'v8::Isolate'
      v8::Isolate::GCEpilogueCallback callback) {
      ~~~~~~~~~~~~~^
    ../../nan/nan.h:601:20: error: no type named 'GCPrologueCallback' in 'v8::Isolate'
      v8::Isolate::GCPrologueCallback callback
      ~~~~~~~~~~~~~^
    ../../nan/nan.h:607:20: error: no type named 'GCPrologueCallback' in 'v8::Isolate'
      v8::Isolate::GCPrologueCallback callback) {
      ~~~~~~~~~~~~~^
    4 errors generated.
    make: *** [Release/obj.target/lwip_decoder/src/decoder/init.o] Error 1
    gyp ERR! build error
    gyp ERR! stack Error: `make` failed with exit code: 2
    gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
    gyp ERR! stack     at emitTwo (events.js:106:13)
    gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
    gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
    gyp ERR! System Darwin 15.2.0
    gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
    gyp ERR! cwd /path
    gyp ERR! node -v v6.2.2
    gyp ERR! node-gyp -v v3.3.1
    gyp ERR! not ok

    npm ERR! Darwin 15.2.0
    npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "i" "lwip"
    npm ERR! node v6.2.2
    npm ERR! npm  v3.9.5
    npm ERR! code ELIFECYCLE

    npm ERR! lwip@0.0.8 install: `node-gyp rebuild`
    npm ERR! Exit status 1
    npm ERR!
    npm ERR! Failed at the lwip@0.0.8 install script 'node-gyp rebuild'.
    npm ERR! Make sure you have the latest version of node.js and npm installed.
    npm ERR! If you do, this is most likely a problem with the lwip package,
    npm ERR! not with npm itself.
    npm ERR! Tell the author that this fails on your system:
    npm ERR!     node-gyp rebuild
    npm ERR! You can get information on how to open an issue for this project with:
    npm ERR!     npm bugs lwip
    npm ERR! Or if that isn't available, you can get their info via:
    npm ERR!     npm owner ls lwip
    npm ERR! There is likely additional logging output above.

    npm ERR! Please include the following file with any support request:
    npm ERR!     /path

**Comment by samzilverberg** [comment]
0.0.9 works
https://github.com/EyalAr/lwip/releases/tag/v0.0.9

**Comment by arkadiusz-wieczorek** [comment]
I have also problem with lwip under Node v6.2.2 :<

```bash
arkadiusz@arkadiusz-ThinkPad-T450s:~/Projects/Placetag$ npm i lwip

> lwip@0.0.9 install /home/arkadiusz/Projects/Placetag/node_modules/lwip
> node-gyp rebuild

make: Entering directory '/home/arkadiusz/Projects/Placetag/node_modules/lwip/build'
  CXX(target) Release/obj.target/lwip_decoder/src/decoder/init.o
/opt/gcc-5.3.1/libexec/gcc/x86_64-unknown-linux-gnu/5.3.1/cc1plus: error while loading shared libraries: libisl.so.13: cannot open shared object file: No such file or directory
lwip_decoder.target.mk:162: recipe for target 'Release/obj.target/lwip_decoder/src/decoder/init.o' failed
make: *** [Release/obj.target/lwip_decoder/src/decoder/init.o] Error 1
make: Leaving directory '/home/arkadiusz/Projects/Placetag/node_modules/lwip/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Linux 4.5.4-ext73-45.4-k8
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/arkadiusz/Projects/Placetag/node_modules/lwip
gyp ERR! node -v v6.2.2
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok 
npm WARN cls-bluebird@1.0.1 requires a peer of continuation-local-storage@~3 but none was installed.
npm WARN placetag-app@0.1.0 No repository field.
npm ERR! Linux 4.5.4-ext73-45.4-k8
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "i" "lwip"
npm ERR! node v6.2.2
npm ERR! npm  v3.10.2
npm ERR! code ELIFECYCLE

npm ERR! lwip@0.0.9 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the lwip@0.0.9 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the lwip package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs lwip
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls lwip
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/arkadiusz/Projects/Placetag/npm-debug.log
```

**Comment by samzilverberg** [comment]
``` /opt/gcc-5.3.1/libexec/gcc/x86_64-unknown-linux-gnu/5.3.1/cc1plus: error while loading shared libraries: libisl.so.13: cannot open shared object file: No such file or directory ```

looks like you have bigger problems, non lwip related.
your gcc compiler is failing to find a pretty basic shared library.
i'd suggest you google it.

**Comment by arkadiusz-wieczorek** [comment]
You are right I will search it.
