### ISSUE TITLE
Module version mismatch

### ISSUE THREAD

**Issue by littledu** [EyalAr/lwip#264]
**node version:**   6.2.0
**npm version:**    3.8.9

I installed lwip in node@6.2.0, the installation process is very smooth, when i run, the following error came:

```
Error: Module version mismatch. Expected 47, got 48.
    at Error (native)
    at Object.Module._extensions..node (module.js:423:18)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at bindings (/Users/littledu/code/tmt-workflow/node_modules/bindings/bindings.js:76:44)
    at /Users/littledu/code/tmt-workflow/node_modules/lwip/lib/Image.js:3:41
    at Object.<anonymous> (/Users/littledu/code/tmt-workflow/node_modules/lwip/lib/Image.js:16:3)
    at Module._compile (module.js:398:26)
```

I have to re-implement `node-gyp rebuild` , still not work with the same error message. So how should i do to fix this? thanks.

**Comment by sharpfuryz** [comment]
Same issue, but different version numbers 
`/node_modules/bindings/bindings.js:83 Uncaught Error: Module version mismatch. Expected 48, got 14.
    at Error (native)
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:158:20)
    at Object.Module._extensions..node (module.js:568:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:158:20)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at bindings (/node_modules/bindings/bindings.js:76:44)
    at /node_modules/lwip/lib/Image.js:3:41
    at Object.<anonymous> (/node_modules/lwip/lib/Image.js:16:3)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)`

**Comment by antoinepairet** [comment]
The message says there is a mismatch between

1. V8 version used to compile `lwip`
2. V8 version used to run `lwip`

Are you using something like `electron` ?
Please make sure the same version of `nodejs` is used to compile `lwip` and execute your code. If you upgraded `nodejs` you should recompile `lwip`.
