### ISSUE TITLE
it's not working on ubuntu but it's woking on mac os 

### ISSUE THREAD

**Issue by bossbossk20** [EyalAr/lwip#266]
Ubuntu 16.04 

rror: Could not locate the bindings file. Tried:
 → /home/superman/nextzy-agile-board/node_modules/lwip/build/lwip_image.node
 → /home/superman/nextzy-agile-board/node_modules/lwip/build/Debug/lwip_image.node
 → /home/superman/nextzy-agile-board/node_modules/lwip/build/Release/lwip_image.node
 → /home/superman/nextzy-agile-board/node_modules/lwip/out/Debug/lwip_image.node
 → /home/superman/nextzy-agile-board/node_modules/lwip/Debug/lwip_image.node
 → /home/superman/nextzy-agile-board/node_modules/lwip/out/Release/lwip_image.node
 → /home/superman/nextzy-agile-board/node_modules/lwip/Release/lwip_image.node
 → /home/superman/nextzy-agile-board/node_modules/lwip/build/default/lwip_image.node
 → /home/superman/nextzy-agile-board/node_modules/lwip/compiled/6.2.2/linux/x64/lwip_image.node
    at bindings (/home/superman/nextzy-agile-board/node_modules/bindings/bindings.js:88:9)
    at /home/superman/nextzy-agile-board/node_modules/lwip/lib/Image.js:3:41
    at Object.<anonymous> (/home/superman/nextzy-agile-board/node_modules/lwip/lib/Image.js:16:3)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at /home/superman/nextzy-agile-board/node_modules/lwip/lib/ImagePrototypeInit.js:3:17
    at Object.<anonymous> (/home/superman/nextzy-agile-board/node_modules/lwip/lib/ImagePrototypeInit.js:620:3)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)

**Comment by mdunn85** [comment]
sudo apt-get install -y build-essential

worked for me
