### ISSUE TITLE
node-gyp rebuild error

### ISSUE THREAD

**Issue by Undefitied** [EyalAr/lwip#277]
`> buffertools@2.1.4 install /var/www/myapp/node_modules/buffertools

> node-gyp rebuild

make: Entering directory `/var/www/myapp/node_modules/buffertools/build'
  CXX(target) Release/obj.target/buffertools/buffertools.o
In file included from /root/.node-gyp/6.6.0/include/node/node.h:42,
                 from ../buffertools.cc:17:
/root/.node-gyp/6.6.0/include/node/v8.h:345: error: expected unqualified-id before ‘using’
/root/.node-gyp/6.6.0/include/node/v8.h: In constructor ‘v8::MaybeLocal<T>::MaybeLocal()’:
/root/.node-gyp/6.6.0/include/node/v8.h:362: error: ‘nullptr’ was not declared in this scope
/root/.node-gyp/6.6.0/include/node/v8.h: In member function ‘bool v8::MaybeLocal<T>::IsEmpty() const’:
/root/.node-gyp/6.6.0/include/node/v8.h:369: error: ‘nullptr’ was not declared in this scope
/root/.node-gyp/6.6.0/include/node/v8.h: In member function ‘bool v8::MaybeLocal<T>::ToLocal(v8::Local<S>*) const’:
/root/.node-gyp/6.6.0/include/node/v8.h:373: error: ‘nullptr’ was not declared in this scope
/root/.node-gyp/6.6.0/include/node/v8.h: In member function ‘bool v8::WeakCallbackInfo<T>::IsFirstPass() const’:
/root/.node-gyp/6.6.0/include/node/v8.h:441: error: ‘nullptr’ was not declared in this scope
/root/.node-gyp/6.6.0/include/node/v8.h: At global scope:
/root/.node-gyp/6.6.0/include/node/v8.h:481: error: expected unqualified-id before ‘using’
/root/.node-gyp/6.6.0/include/node/v8.h: In constructor ‘v8::Global<T>::Global()’:
/root/.node-gyp/6.6.0/include/node/v8.h:820: error: ‘nullptr’ was not declared in this scope
/root/.node-gyp/6.6.0/include/node/v8.h: In constructor ‘v8::Global<T>::Global(v8::Global<T>&&)’:
/root/.node-gyp/6.6.0/include/node/v8.h:845: error: ‘nullptr’ was not declared in this scope
/root/.node-gyp/6.6.0/include/node/v8.h: In member function ‘v8::Global<T>& v8::Global<T>::operator=(v8::Global<S>&&)’:
/root/.node-gyp/6.6.0/include/node/v8.h:857: error: ‘nullptr’ was not declared in this scope
/root/.node-gyp/6.6.0/include/node/v8.h: At global scope:
/root/.node-gyp/6.6.0/include/node/v8.h:882: error: expected unqualified-id before ‘using’
/root/.node-gyp/6.6.0/include/node/v8.h:1119: error: ‘nullptr’ was not declared in this scope
/root/.node-gyp/6.6.0/include/node/v8.h:1125: error: ‘nullptr’ was not declared in this scope
/root/.node-gyp/6.6.0/include/node/v8.h: In member function ‘v8::MaybeLocal<v8::Object> v8::Function::NewInstance(v8::Local<v8::Context>) const’:
/root/.node-gyp/6.6.0/include/node/v8.h:3277: error: ‘nullptr’ was not declared in this scope
/root/.node-gyp/6.6.0/include/node/v8.h: At global scope:
/root/.node-gyp/6.6.0/include/node/v8.h:4497: error: ‘nullptr’ was not declared in this scope
/root/.node-gyp/6.6.0/include/node/v8.h:4513: error: ‘nullptr’ was not declared in this scope
/root/.node-gyp/6.6.0/include/node/v8.h: In member function ‘v8::Local<T> v8::MaybeLocal<T>::ToLocalChecked()’:
/root/.node-gyp/6.6.0/include/node/v8.h:7537: error: ‘nullptr’ was not declared in this scope
../buffertools.cc: At global scope:
../buffertools.cc:32: error: ‘v8::Handle’ has not been declared
../buffertools.cc:492: error: variable or field ‘RegisterModule’ declared void
../buffertools.cc:492: error: ‘Handle’ was not declared in this scope
../buffertools.cc:492: error: expected primary-expression before ‘>’ token
../buffertools.cc:492: error: ‘target’ was not declared in this scope
../buffertools.cc:506: error: ‘RegisterModule’ was not declared in this scope
../buffertools.cc:506: error: too many initializers for ‘node::node_module’
make: *** [Release/obj.target/buffertools/buffertools.o] Error 1
make: Leaving directory`/var/www/myapp/node_modules/buffertools/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 2.6.32-042stab116.1
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /var/www/myapp/node_modules/buffertools
gyp ERR! node -v v6.6.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok

> secp256k1@3.0.1 install /var/www/myapp/node_modules/secp256k1
> npm run rebuild
> 
> secp256k1@3.0.1 rebuild /var/www/myapp/node_modules/secp256k1
> node-gyp rebuild

make: Entering directory `/var/www/myapp/node_modules/secp256k1/build'
  CXX(target) Release/obj.target/secp256k1/src/addon.o
In file included from ../src/addon.cc:2:
../../nan/nan.h:43:3: error: #error This version of node/NAN/v8 requires a C++11 compiler
In file included from /root/.node-gyp/6.6.0/include/node/node.h:42,
                 from ../src/addon.cc:1:
/root/.node-gyp/6.6.0/include/node/v8.h:345: error: expected unqualified-id before ‘using’
/root/.node-gyp/6.6.0/include/node/v8.h: In constructor ‘v8::MaybeLocal<T>::MaybeLocal()’:
/root/.node-gyp/6.6.0/include/node/v8.h:362: error: ‘nullptr’ was not declared in this scope
/root/.node-gyp/6.6.0/include/node/v8.h: In member function ‘bool v8::MaybeLocal<T>::IsEmpty() const’:
/root/.node-gyp/6.6.0/include/node/v8.h:369: error: ‘nullptr’ was not declared in this scope
/root/.node-gyp/6.6.0/include/node/v8.h: In member function ‘bool v8::MaybeLocal<T>::ToLocal(v8::Local<S>*) const’:
/root/.node-gyp/6.6.0/include/node/v8.h:373: error: ‘nullptr’ was not declared in this scope
/root/.node-gyp/6.6.0/include/node/v8.h: In member function ‘bool v8::WeakCallbackInfo<T>::IsFirstPass() const’:
/root/.node-gyp/6.6.0/include/node/v8.h:441: error: ‘nullptr’ was not declared in this scope
/root/.node-gyp/6.6.0/include/node/v8.h: At global scope:
/root/.node-gyp/6.6.0/include/node/v8.h:481: error: expected unqualified-id before ‘using’
/root/.node-gyp/6.6.0/include/node/v8.h: In constructor ‘v8::Global<T>::Global()’:
/root/.node-gyp/6.6.0/include/node/v8.h:820: error: ‘nullptr’ was not declared in this scope
/root/.node-gyp/6.6.0/include/node/v8.h: In constructor ‘v8::Global<T>::Global(v8::Global<T>&&)’:
/root/.node-gyp/6.6.0/include/node/v8.h:845: error: ‘nullptr’ was not declared in this scope
/root/.node-gyp/6.6.0/include/node/v8.h: In member function ‘v8::Global<T>& v8::Global<T>::operator=(v8::Global<S>&&)’:
/root/.node-gyp/6.6.0/include/node/v8.h:857: error: ‘nullptr’ was not declared in this scope
/root/.node-gyp/6.6.0/include/node/v8.h: At global scope:
/root/.node-gyp/6.6.0/include/node/v8.h:882: error: expected unqualified-id before ‘using’
/root/.node-gyp/6.6.0/include/node/v8.h:1119: error: ‘nullptr’ was not declared in this scope
/root/.node-gyp/6.6.0/include/node/v8.h:1125: error: ‘nullptr’ was not declared in this scope
/root/.node-gyp/6.6.0/include/node/v8.h: In member function ‘v8::MaybeLocal<v8::Object> v8::Function::NewInstance(v8::Local<v8::Context>) const’:
/root/.node-gyp/6.6.0/include/node/v8.h:3277: error: ‘nullptr’ was not declared in this scope
/root/.node-gyp/6.6.0/include/node/v8.h: At global scope:
/root/.node-gyp/6.6.0/include/node/v8.h:4497: error: ‘nullptr’ was not declared in this scope
/root/.node-gyp/6.6.0/include/node/v8.h:4513: error: ‘nullptr’ was not declared in this scope
/root/.node-gyp/6.6.0/include/node/v8.h: In member function ‘v8::Local<T> v8::MaybeLocal<T>::ToLocalChecked()’:
/root/.node-gyp/6.6.0/include/node/v8.h:7537: error: ‘nullptr’ was not declared in this scope
In file included from ../../nan/nan.h:190,
                 from ../src/addon.cc:2:
../../nan/nan_maybe_43_inl.h: At global scope:
../../nan/nan_maybe_43_inl.h:13: error: expected unqualified-id before ‘using’
../../nan/nan_maybe_43_inl.h:16: error: expected unqualified-id before ‘using’
../../nan/nan_maybe_43_inl.h:19: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:24: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:31: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:36: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:41: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:46: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:51: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:59: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:64: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:69: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:76: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:83: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:91: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:98: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:108: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:114: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:118: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:125: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:130: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:135: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:139: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:145: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:150: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:156: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:162: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:168: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:174: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:180: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:186: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:194: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:201: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:205: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:209: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:213: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:217: error: expected initializer before ‘<’ token
../src/addon.cc:47: error: expected ‘}’ at end of input
cc1plus: warning: unrecognized command line option "-Wno-maybe-uninitialized"
make: *** [Release/obj.target/secp256k1/src/addon.o] Error 1
make: Leaving directory`/var/www/myapp/node_modules/secp256k1/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 2.6.32-042stab116.1
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /var/www/myapp/node_modules/secp256k1
gyp ERR! node -v v6.6.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok

npm ERR! Linux 2.6.32-042stab116.1
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "rebuild"
npm ERR! node v6.6.0
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! secp256k1@3.0.1 rebuild: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the secp256k1@3.0.1 rebuild script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the secp256k1 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs secp256k1
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls secp256k1
npm ERR! There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! Please include the following file with any support request:
npm ERR!     /var/www/myapp/node_modules/secp256k1/npm-debug.log

> lwip@0.0.9 install /var/www/myapp/node_modules/lwip
> node-gyp rebuild

make: Entering directory `/var/www/myapp/node_modules/lwip/build'
  CXX(target) Release/obj.target/lwip_decoder/src/decoder/init.o
In file included from ../src/decoder/decoder.h:13,
                 from ../src/decoder/init.cpp:1:
../../nan/nan.h:43:3: error: #error This version of node/NAN/v8 requires a C++11 compiler
In file included from /root/.node-gyp/6.6.0/include/node/node.h:42,
                 from ../src/decoder/decoder.h:11,
                 from ../src/decoder/init.cpp:1:
/root/.node-gyp/6.6.0/include/node/v8.h:345: error: expected unqualified-id before ‘using’
/root/.node-gyp/6.6.0/include/node/v8.h: In constructor ‘v8::MaybeLocal<T>::MaybeLocal()’:
/root/.node-gyp/6.6.0/include/node/v8.h:362: error: ‘nullptr’ was not declared in this scope
/root/.node-gyp/6.6.0/include/node/v8.h: In member function ‘bool v8::MaybeLocal<T>::IsEmpty() const’:
/root/.node-gyp/6.6.0/include/node/v8.h:369: error: ‘nullptr’ was not declared in this scope
/root/.node-gyp/6.6.0/include/node/v8.h: In member function ‘bool v8::MaybeLocal<T>::ToLocal(v8::Local<S>*) const’:
/root/.node-gyp/6.6.0/include/node/v8.h:373: error: ‘nullptr’ was not declared in this scope
/root/.node-gyp/6.6.0/include/node/v8.h: In member function ‘bool v8::WeakCallbackInfo<T>::IsFirstPass() const’:
/root/.node-gyp/6.6.0/include/node/v8.h:441: error: ‘nullptr’ was not declared in this scope
/root/.node-gyp/6.6.0/include/node/v8.h: At global scope:
/root/.node-gyp/6.6.0/include/node/v8.h:481: error: expected unqualified-id before ‘using’
/root/.node-gyp/6.6.0/include/node/v8.h: In constructor ‘v8::Global<T>::Global()’:
/root/.node-gyp/6.6.0/include/node/v8.h:820: error: ‘nullptr’ was not declared in this scope
/root/.node-gyp/6.6.0/include/node/v8.h: In constructor ‘v8::Global<T>::Global(v8::Global<T>&&)’:
/root/.node-gyp/6.6.0/include/node/v8.h:845: error: ‘nullptr’ was not declared in this scope
/root/.node-gyp/6.6.0/include/node/v8.h: In member function ‘v8::Global<T>& v8::Global<T>::operator=(v8::Global<S>&&)’:
/root/.node-gyp/6.6.0/include/node/v8.h:857: error: ‘nullptr’ was not declared in this scope
/root/.node-gyp/6.6.0/include/node/v8.h: At global scope:
/root/.node-gyp/6.6.0/include/node/v8.h:882: error: expected unqualified-id before ‘using’
/root/.node-gyp/6.6.0/include/node/v8.h:1119: error: ‘nullptr’ was not declared in this scope
/root/.node-gyp/6.6.0/include/node/v8.h:1125: error: ‘nullptr’ was not declared in this scope
/root/.node-gyp/6.6.0/include/node/v8.h: In member function ‘v8::MaybeLocal<v8::Object> v8::Function::NewInstance(v8::Local<v8::Context>) const’:
/root/.node-gyp/6.6.0/include/node/v8.h:3277: error: ‘nullptr’ was not declared in this scope
/root/.node-gyp/6.6.0/include/node/v8.h: At global scope:
/root/.node-gyp/6.6.0/include/node/v8.h:4497: error: ‘nullptr’ was not declared in this scope
/root/.node-gyp/6.6.0/include/node/v8.h:4513: error: ‘nullptr’ was not declared in this scope
/root/.node-gyp/6.6.0/include/node/v8.h: In member function ‘v8::Local<T> v8::MaybeLocal<T>::ToLocalChecked()’:
/root/.node-gyp/6.6.0/include/node/v8.h:7537: error: ‘nullptr’ was not declared in this scope
In file included from ../../nan/nan.h:190,
                 from ../src/decoder/decoder.h:13,
                 from ../src/decoder/init.cpp:1:
../../nan/nan_maybe_43_inl.h: At global scope:
../../nan/nan_maybe_43_inl.h:13: error: expected unqualified-id before ‘using’
../../nan/nan_maybe_43_inl.h:16: error: expected unqualified-id before ‘using’
../../nan/nan_maybe_43_inl.h:19: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:24: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:31: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:36: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:41: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:46: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:51: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:59: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:64: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:69: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:76: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:83: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:91: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:98: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:108: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:114: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:118: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:125: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:130: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:135: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:139: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:145: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:150: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:156: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:162: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:168: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:174: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:180: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:186: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:194: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:201: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:205: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:209: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:213: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:217: error: expected initializer before ‘<’ token
../src/decoder/init.cpp:38: error: expected ‘}’ at end of input
../../nan/nan_callbacks_12_inl.h:167: warning: ‘void Nan::imp::FunctionCallbackWrapper(const v8::FunctionCallbackInfo<v8::Value>&)’ defined but not used
../../nan/nan_callbacks_12_inl.h:181: warning: ‘void Nan::imp::GetterCallbackWrapper(v8::Local<v8::Name>, const v8::PropertyCallbackInfo<v8::Value>&)’ defined but not used
../../nan/nan_callbacks_12_inl.h:197: warning: ‘void Nan::imp::SetterCallbackWrapper(v8::Local<v8::Name>, v8::Local<v8::Value>, const v8::PropertyCallbackInfo<void>&)’ defined but not used
../../nan/nan_callbacks_12_inl.h:253: warning: ‘void Nan::imp::PropertyGetterCallbackWrapper(v8::Local<v8::Name>, const v8::PropertyCallbackInfo<v8::Value>&)’ defined but not used
../../nan/nan_callbacks_12_inl.h:270: warning: ‘void Nan::imp::PropertySetterCallbackWrapper(v8::Local<v8::Name>, v8::Local<v8::Value>, const v8::PropertyCallbackInfo<v8::Value>&)’ defined but not used
../../nan/nan_callbacks_12_inl.h:290: warning: ‘void Nan::imp::PropertyEnumeratorCallbackWrapper(const v8::PropertyCallbackInfo<v8::Array>&)’ defined but not used
../../nan/nan_callbacks_12_inl.h:306: warning: ‘void Nan::imp::PropertyDeleterCallbackWrapper(v8::Local<v8::Name>, const v8::PropertyCallbackInfo<v8::Boolean>&)’ defined but not used
../../nan/nan_callbacks_12_inl.h:323: warning: ‘void Nan::imp::PropertyQueryCallbackWrapper(v8::Local<v8::Name>, const v8::PropertyCallbackInfo<v8::Integer>&)’ defined but not used
../../nan/nan_callbacks_12_inl.h:428: warning: ‘void Nan::imp::IndexGetterCallbackWrapper(uint32_t, const v8::PropertyCallbackInfo<v8::Value>&)’ defined but not used
../../nan/nan_callbacks_12_inl.h:444: warning: ‘void Nan::imp::IndexSetterCallbackWrapper(uint32_t, v8::Local<v8::Value>, const v8::PropertyCallbackInfo<v8::Value>&)’ defined but not used
../../nan/nan_callbacks_12_inl.h:464: warning: ‘void Nan::imp::IndexEnumeratorCallbackWrapper(const v8::PropertyCallbackInfo<v8::Array>&)’ defined but not used
../../nan/nan_callbacks_12_inl.h:480: warning: ‘void Nan::imp::IndexDeleterCallbackWrapper(uint32_t, const v8::PropertyCallbackInfo<v8::Boolean>&)’ defined but not used
../../nan/nan_callbacks_12_inl.h:496: warning: ‘void Nan::imp::IndexQueryCallbackWrapper(uint32_t, const v8::PropertyCallbackInfo<v8::Integer>&)’ defined but not used
make: *** [Release/obj.target/lwip_decoder/src/decoder/init.o] Error 1
make: Leaving directory`/var/www/myapp/node_modules/lwip/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 2.6.32-042stab116.1
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /var/www/myapp/node_modules/lwip
gyp ERR! node -v v6.6.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: buffertools@2.1.4 (node_modules/buffertools):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: buffertools@2.1.4 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: secp256k1@3.0.1 (node_modules/secp256k1):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: secp256k1@3.0.1 install: `npm run rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
npm ERR! Linux 2.6.32-042stab116.1
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "i"
npm ERR! node v6.6.0
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE

npm ERR! lwip@0.0.9 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the lwip@0.0.9 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the lwip package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs lwip
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls lwip
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /var/www/myapp/npm-debug.log
`

**Comment by jpdevries** [comment]
i'm experiencing this as well

**Comment by anonrig** [comment]
me too.

**Comment by Undefitied** [comment]
similar issue is still open from july

**Comment by jpdevries** [comment]
For an Azure deployment I switched to `node-lwip` and included 

``` json
"optionalDependencies": {
  "windows-build-tools": "*"
},
```

in package.json to fix this. If you still have issues you might have to use the force `--force`. 

I am also experiencing this same issue on a Linux server and haven't been able to get it working with `lwip` or `node-lwip` yet.

https://github.com/jpdevries/makeanico/issues/7#issuecomment-250922986
