### ISSUE TITLE
node-gyp rebuild on mac

### ISSUE THREAD

**Issue by UdeRox** [EyalAr/lwip#278]
Hi,
I'm getting below error while when installing lwip.I have updated the npm and node versions on my lap, now I couldn't run the "npm install" command within my project. below is the error I'm getting

`udeshikaperera$ npm install

> lwip@0.0.8 install /Users/udeshikaperera/Project/Otenro/node_modules/lwip
> node-gyp rebuild

  CXX(target) Release/obj.target/lwip_decoder/src/decoder/init.o
In file included from ../src/decoder/init.cpp:1:
In file included from ../src/decoder/decoder.h:13:
../../nan/nan.h:590:20: error: no type named 'GCEpilogueCallback' in 'v8::Isolate'
      v8::Isolate::GCEpilogueCallback callback
      ~~~~~~~~~~~~~^
../../nan/nan.h:596:20: error: no type named 'GCEpilogueCallback' in 'v8::Isolate'
      v8::Isolate::GCEpilogueCallback callback) {
      ~~~~~~~~~~~~~^
../../nan/nan.h:601:20: error: no type named 'GCPrologueCallback' in 'v8::Isolate'
      v8::Isolate::GCPrologueCallback callback
      ~~~~~~~~~~~~~^
../../nan/nan.h:607:20: error: no type named 'GCPrologueCallback' in 'v8::Isolate'
      v8::Isolate::GCPrologueCallback callback) {
      ~~~~~~~~~~~~~^
4 errors generated.
make: **\* [Release/obj.target/lwip_decoder/src/decoder/init.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Darwin 15.6.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/udeshikaperera/Project/Otenro/node_modules/lwip
gyp ERR! node -v v6.7.0
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok
npm WARN mongodb-core@1.2.31 requires a peer of kerberos@~0.0 but none was installed.
npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v6.7.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE

npm ERR! lwip@0.0.8 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the lwip@0.0.8 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the lwip package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs lwip
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls lwip
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/udeshikaperera/Project/Otenro/npm-debug.log`

 **/Users/udeshikaperera/Project/Otenro/npm-debug.log**

`463 verbose lifecycle lwip@0.0.8~install: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/udeshikaperera/Project/Otenro/node_modules/lwip/node_modules/.bin:/Users/udeshikaperera/Project/Otenro/node_modules/.bin:/usr/local/bin:/Users/udeshikaperera/softwares/android/adt-bundle-mac-x86_64-20140702/sdk/tools:/Users/udeshikaperera/softwares/android/adt-bundle-mac-x86_64-20140702/sdk/platform-tools:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin
464 verbose lifecycle lwip@0.0.8~install: CWD: /Users/udeshikaperera/Project/Otenro/node_modules/lwip
465 silly lifecycle lwip@0.0.8~install: Args: [ '-c', 'node-gyp rebuild' ]
466 silly lifecycle lwip@0.0.8~install: Returned: code: 1  signal: null
467 info lifecycle lwip@0.0.8~install: Failed to exec install script
468 verbose unlock done using /Users/udeshikaperera/.npm/_locks/staging-5b3b8fb67369ed0b.lock for /Users/udeshikaperera/Project/Otenro/node_modules/.staging
469 silly rollbackFailedOptional Starting
470 silly rollbackFailedOptional Finishing
471 silly runTopLevelLifecycles Starting
472 silly runTopLevelLifecycles Finishing
473 silly install printInstalled
474 warn mongodb-core@1.2.31 requires a peer of kerberos@~0.0 but none was installed.
475 verbose stack Error: lwip@0.0.8 install:`node-gyp rebuild`
475 verbose stack Exit status 1
475 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:242:16)
475 verbose stack     at emitTwo (events.js:106:13)
475 verbose stack     at EventEmitter.emit (events.js:191:7)
475 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
475 verbose stack     at emitTwo (events.js:106:13)
475 verbose stack     at ChildProcess.emit (events.js:191:7)
475 verbose stack     at maybeClose (internal/child_process.js:877:16)
475 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
476 verbose pkgid lwip@0.0.8
477 verbose cwd /Users/udeshikaperera/Project/Otenro
478 error Darwin 15.6.0
479 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
480 error node v6.7.0
481 error npm  v3.10.3
482 error code ELIFECYCLE
483 error lwip@0.0.8 install:`node-gyp rebuild`
483 error Exit status 1
484 error Failed at the lwip@0.0.8 install script 'node-gyp rebuild'.
484 error Make sure you have the latest version of node.js and npm installed.
484 error If you do, this is most likely a problem with the lwip package,
484 error not with npm itself.
484 error Tell the author that this fails on your system:
484 error     node-gyp rebuild
484 error You can get information on how to open an issue for this project with:
484 error     npm bugs lwip
484 error Or if that isn't available, you can get their info via:
484 error     npm owner ls lwip
484 error There is likely additional logging output above.
485 verbose exit [ 1, true ]`

**Comment by milewski** [comment]
me too... how to do?

**Comment by frangeris** [comment]
#263 @EyalAr This is stopping a lot of installs, we're stuck with this issue, how to fix it?

Thanks

**Comment by milewski** [comment]
i gave up ~~ i was using this library [sprity](https://github.com/sprity/sprity) which by defaults uses lwip... i couldnt get it install so i moved to another engine [https://github.com/sprity/sprity-gm](https://github.com/sprity/sprity-gm) ¯\_(ツ)_/¯

**Comment by mikegleasonjr** [comment]
@EyalAr seriously? It's been a year. Thanks @Milewski, will also swap.

**Comment by evanjmg** [comment]
+1

**Comment by ghost** [comment]
+1

**Comment by birchb** [comment]
+1

I cloned the repository and ran nom install. Here's the debug log:

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'install' ]
2 info using npm@4.5.0
3 info using node@v6.10.3
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly install normalizeTree
8 silly loadCurrentTree Finishing
9 silly loadIdealTree Starting
10 silly install loadIdealTree
11 silly cloneCurrentTree Starting
12 silly install cloneCurrentTreeToIdealTree
13 silly cloneCurrentTree Finishing
14 silly loadShrinkwrap Starting
15 silly install loadShrinkwrap
16 silly loadShrinkwrap Finishing
17 silly loadAllDepsIntoIdealTree Starting
18 silly install loadAllDepsIntoIdealTree
19 silly loadAllDepsIntoIdealTree Finishing
20 silly loadIdealTree Finishing
21 silly currentTree lwip@0.0.9
21 silly currentTree ├── abbrev@1.0.9
21 silly currentTree ├── align-text@0.1.4
21 silly currentTree ├── amdefine@1.0.1
21 silly currentTree ├── ansi-regex@2.1.1
21 silly currentTree ├── ansi-styles@2.2.1
21 silly currentTree ├── argparse@1.0.9
21 silly currentTree ├── asn1@0.2.3
21 silly currentTree ├── assert-plus@0.2.0
21 silly currentTree ├── async@2.4.0
21 silly currentTree ├── asynckit@0.4.0
21 silly currentTree ├── aws-sign2@0.6.0
21 silly currentTree ├── aws4@1.6.0
21 silly currentTree ├── balanced-match@0.4.2
21 silly currentTree ├── bcrypt-pbkdf@1.0.1
21 silly currentTree ├── bindings@1.2.1
21 silly currentTree ├── boom@2.10.1
21 silly currentTree ├── brace-expansion@1.1.7
21 silly currentTree ├── camelcase@1.2.1
21 silly currentTree ├── caseless@0.11.0
21 silly currentTree ├── center-align@0.1.3
21 silly currentTree ├── chalk@1.1.3
21 silly currentTree ├─┬ cliui@2.1.0
21 silly currentTree │ └── wordwrap@0.0.2
21 silly currentTree ├── combined-stream@1.0.5
21 silly currentTree ├── commander@2.9.0
21 silly currentTree ├── concat-map@0.0.1
21 silly currentTree ├── coveralls@2.13.1
21 silly currentTree ├── cryptiles@2.0.5
21 silly currentTree ├─┬ dashdash@1.14.1
21 silly currentTree │ └── assert-plus@1.0.0
21 silly currentTree ├── debug@2.2.0
21 silly currentTree ├── decamelize@1.2.0
21 silly currentTree ├── decree@0.0.6
21 silly currentTree ├── deep-is@0.1.3
21 silly currentTree ├── delayed-stream@1.0.0
21 silly currentTree ├── diff@1.4.0
21 silly currentTree ├── ecc-jsbn@0.1.1
21 silly currentTree ├── escape-string-regexp@1.0.5
21 silly currentTree ├── escodegen@1.8.1
21 silly currentTree ├── esprima@2.7.3
21 silly currentTree ├── estraverse@1.9.3
21 silly currentTree ├── esutils@2.0.2
21 silly currentTree ├── extend@3.0.1
21 silly currentTree ├── extsprintf@1.0.2
21 silly currentTree ├── fast-levenshtein@2.0.6
21 silly currentTree ├── forever-agent@0.6.1
21 silly currentTree ├── form-data@2.1.4
21 silly currentTree ├── generate-function@2.0.0
21 silly currentTree ├── generate-object-property@1.2.0
21 silly currentTree ├─┬ getpass@0.1.7
21 silly currentTree │ └── assert-plus@1.0.0
21 silly currentTree ├── glob@5.0.15
21 silly currentTree ├── graceful-readlink@1.0.1
21 silly currentTree ├── growl@1.9.2
21 silly currentTree ├─┬ handlebars@4.0.8
21 silly currentTree │ ├── async@1.5.2
21 silly currentTree │ └── source-map@0.4.4
21 silly currentTree ├── har-validator@2.0.6
21 silly currentTree ├── has-ansi@2.0.0
21 silly currentTree ├── has-flag@1.0.0
21 silly currentTree ├── hawk@3.1.3
21 silly currentTree ├── hoek@2.16.3
21 silly currentTree ├── http-signature@1.1.1
21 silly currentTree ├── inflight@1.0.6
21 silly currentTree ├── inherits@2.0.3
21 silly currentTree ├── is-buffer@1.1.5
21 silly currentTree ├── is-my-json-valid@2.16.0
21 silly currentTree ├── is-property@1.0.2
21 silly currentTree ├── is-typedarray@1.0.0
21 silly currentTree ├── isexe@2.0.0
21 silly currentTree ├── isstream@0.1.2
21 silly currentTree ├─┬ istanbul@0.4.5
21 silly currentTree │ ├── async@1.5.2
21 silly currentTree │ └── supports-color@3.2.3
21 silly currentTree ├─┬ jade@0.26.3
21 silly currentTree │ ├── commander@0.6.1
21 silly currentTree │ └── mkdirp@0.3.0
21 silly currentTree ├── jodid25519@1.0.2
21 silly currentTree ├── js-yaml@3.6.1
21 silly currentTree ├── jsbn@0.1.1
21 silly currentTree ├── json-schema@0.2.3
21 silly currentTree ├── json-stringify-safe@5.0.1
21 silly currentTree ├── jsonpointer@4.0.1
21 silly currentTree ├─┬ jsprim@1.4.0
21 silly currentTree │ └── assert-plus@1.0.0
21 silly currentTree ├── kind-of@3.2.0
21 silly currentTree ├── lazy-cache@1.0.4
21 silly currentTree ├── lcov-parse@0.0.10
21 silly currentTree ├── levn@0.3.0
21 silly currentTree ├── lodash-node@2.4.1
21 silly currentTree ├── lodash@4.17.4
21 silly currentTree ├── log-driver@1.2.5
21 silly currentTree ├── longest@1.0.1
21 silly currentTree ├── lru-cache@2.7.3
21 silly currentTree ├── mime-db@1.27.0
21 silly currentTree ├── mime-types@2.1.15
21 silly currentTree ├── minimatch@3.0.4
21 silly currentTree ├── minimist@1.2.0
21 silly currentTree ├─┬ mkdirp@0.5.1
21 silly currentTree │ └── minimist@0.0.8
21 silly currentTree ├── mocha-lcov-reporter@1.3.0
21 silly currentTree ├─┬ mocha@2.5.3
21 silly currentTree │ ├── commander@2.3.0
21 silly currentTree │ ├── escape-string-regexp@1.0.2
21 silly currentTree │ ├── glob@3.2.11
21 silly currentTree │ ├── minimatch@0.3.0
21 silly currentTree │ └── supports-color@1.2.0
21 silly currentTree ├── ms@0.7.1
21 silly currentTree ├── nan@2.6.2
21 silly currentTree ├── nopt@3.0.6
21 silly currentTree ├── oauth-sign@0.8.2
21 silly currentTree ├── once@1.4.0
21 silly currentTree ├─┬ optimist@0.6.1
21 silly currentTree │ ├── minimist@0.0.10
21 silly currentTree │ └── wordwrap@0.0.3
21 silly currentTree ├── optionator@0.8.2
21 silly currentTree ├── path-is-absolute@1.0.1
21 silly currentTree ├── pinkie-promise@2.0.1
21 silly currentTree ├── pinkie@2.0.4
21 silly currentTree ├── prelude-ls@1.1.2
21 silly currentTree ├── punycode@1.4.1
21 silly currentTree ├── qs@6.3.2
21 silly currentTree ├── repeat-string@1.6.1
21 silly currentTree ├── request@2.79.0
21 silly currentTree ├── resolve@1.1.7
21 silly currentTree ├── right-align@0.1.3
21 silly currentTree ├── should-equal@0.8.0
21 silly currentTree ├── should-format@0.3.2
21 silly currentTree ├── should-type@0.2.0
21 silly currentTree ├── should@8.4.0
21 silly currentTree ├── sigmund@1.0.1
21 silly currentTree ├── sntp@1.0.9
21 silly currentTree ├── source-map@0.2.0
21 silly currentTree ├── sprintf-js@1.0.3
21 silly currentTree ├─┬ sshpk@1.13.0
21 silly currentTree │ └── assert-plus@1.0.0
21 silly currentTree ├── stringstream@0.0.5
21 silly currentTree ├── strip-ansi@3.0.1
21 silly currentTree ├── supports-color@2.0.0
21 silly currentTree ├── to-iso-string@0.0.2
21 silly currentTree ├── tough-cookie@2.3.2
21 silly currentTree ├── tunnel-agent@0.4.3
21 silly currentTree ├── tweetnacl@0.14.5
21 silly currentTree ├── type-check@0.3.2
21 silly currentTree ├─┬ uglify-js@2.8.24
21 silly currentTree │ └── source-map@0.5.6
21 silly currentTree ├── uglify-to-browserify@1.0.2
21 silly currentTree ├── uuid@3.0.1
21 silly currentTree ├── verror@1.3.6
21 silly currentTree ├── which@1.2.14
21 silly currentTree ├── window-size@0.1.0
21 silly currentTree ├── wordwrap@1.0.0
21 silly currentTree ├── wrappy@1.0.2
21 silly currentTree ├── xtend@4.0.1
21 silly currentTree └── yargs@3.10.0
22 silly idealTree lwip@0.0.9
22 silly idealTree ├── abbrev@1.0.9
22 silly idealTree ├── align-text@0.1.4
22 silly idealTree ├── amdefine@1.0.1
22 silly idealTree ├── ansi-regex@2.1.1
22 silly idealTree ├── ansi-styles@2.2.1
22 silly idealTree ├── argparse@1.0.9
22 silly idealTree ├── asn1@0.2.3
22 silly idealTree ├── assert-plus@0.2.0
22 silly idealTree ├── async@2.4.0
22 silly idealTree ├── asynckit@0.4.0
22 silly idealTree ├── aws-sign2@0.6.0
22 silly idealTree ├── aws4@1.6.0
22 silly idealTree ├── balanced-match@0.4.2
22 silly idealTree ├── bcrypt-pbkdf@1.0.1
22 silly idealTree ├── bindings@1.2.1
22 silly idealTree ├── boom@2.10.1
22 silly idealTree ├── brace-expansion@1.1.7
22 silly idealTree ├── camelcase@1.2.1
22 silly idealTree ├── caseless@0.11.0
22 silly idealTree ├── center-align@0.1.3
22 silly idealTree ├── chalk@1.1.3
22 silly idealTree ├─┬ cliui@2.1.0
22 silly idealTree │ └── wordwrap@0.0.2
22 silly idealTree ├── combined-stream@1.0.5
22 silly idealTree ├── commander@2.9.0
22 silly idealTree ├── concat-map@0.0.1
22 silly idealTree ├── coveralls@2.13.1
22 silly idealTree ├── cryptiles@2.0.5
22 silly idealTree ├─┬ dashdash@1.14.1
22 silly idealTree │ └── assert-plus@1.0.0
22 silly idealTree ├── debug@2.2.0
22 silly idealTree ├── decamelize@1.2.0
22 silly idealTree ├── decree@0.0.6
22 silly idealTree ├── deep-is@0.1.3
22 silly idealTree ├── delayed-stream@1.0.0
22 silly idealTree ├── diff@1.4.0
22 silly idealTree ├── ecc-jsbn@0.1.1
22 silly idealTree ├── escape-string-regexp@1.0.5
22 silly idealTree ├── escodegen@1.8.1
22 silly idealTree ├── esprima@2.7.3
22 silly idealTree ├── estraverse@1.9.3
22 silly idealTree ├── esutils@2.0.2
22 silly idealTree ├── extend@3.0.1
22 silly idealTree ├── extsprintf@1.0.2
22 silly idealTree ├── fast-levenshtein@2.0.6
22 silly idealTree ├── forever-agent@0.6.1
22 silly idealTree ├── form-data@2.1.4
22 silly idealTree ├── generate-function@2.0.0
22 silly idealTree ├── generate-object-property@1.2.0
22 silly idealTree ├─┬ getpass@0.1.7
22 silly idealTree │ └── assert-plus@1.0.0
22 silly idealTree ├── glob@5.0.15
22 silly idealTree ├── graceful-readlink@1.0.1
22 silly idealTree ├── growl@1.9.2
22 silly idealTree ├─┬ handlebars@4.0.8
22 silly idealTree │ ├── async@1.5.2
22 silly idealTree │ └── source-map@0.4.4
22 silly idealTree ├── har-validator@2.0.6
22 silly idealTree ├── has-ansi@2.0.0
22 silly idealTree ├── has-flag@1.0.0
22 silly idealTree ├── hawk@3.1.3
22 silly idealTree ├── hoek@2.16.3
22 silly idealTree ├── http-signature@1.1.1
22 silly idealTree ├── inflight@1.0.6
22 silly idealTree ├── inherits@2.0.3
22 silly idealTree ├── is-buffer@1.1.5
22 silly idealTree ├── is-my-json-valid@2.16.0
22 silly idealTree ├── is-property@1.0.2
22 silly idealTree ├── is-typedarray@1.0.0
22 silly idealTree ├── isexe@2.0.0
22 silly idealTree ├── isstream@0.1.2
22 silly idealTree ├─┬ istanbul@0.4.5
22 silly idealTree │ ├── async@1.5.2
22 silly idealTree │ └── supports-color@3.2.3
22 silly idealTree ├─┬ jade@0.26.3
22 silly idealTree │ ├── commander@0.6.1
22 silly idealTree │ └── mkdirp@0.3.0
22 silly idealTree ├── jodid25519@1.0.2
22 silly idealTree ├── js-yaml@3.6.1
22 silly idealTree ├── jsbn@0.1.1
22 silly idealTree ├── json-schema@0.2.3
22 silly idealTree ├── json-stringify-safe@5.0.1
22 silly idealTree ├── jsonpointer@4.0.1
22 silly idealTree ├─┬ jsprim@1.4.0
22 silly idealTree │ └── assert-plus@1.0.0
22 silly idealTree ├── kind-of@3.2.0
22 silly idealTree ├── lazy-cache@1.0.4
22 silly idealTree ├── lcov-parse@0.0.10
22 silly idealTree ├── levn@0.3.0
22 silly idealTree ├── lodash-node@2.4.1
22 silly idealTree ├── lodash@4.17.4
22 silly idealTree ├── log-driver@1.2.5
22 silly idealTree ├── longest@1.0.1
22 silly idealTree ├── lru-cache@2.7.3
22 silly idealTree ├── mime-db@1.27.0
22 silly idealTree ├── mime-types@2.1.15
22 silly idealTree ├── minimatch@3.0.4
22 silly idealTree ├── minimist@1.2.0
22 silly idealTree ├─┬ mkdirp@0.5.1
22 silly idealTree │ └── minimist@0.0.8
22 silly idealTree ├── mocha-lcov-reporter@1.3.0
22 silly idealTree ├─┬ mocha@2.5.3
22 silly idealTree │ ├── commander@2.3.0
22 silly idealTree │ ├── escape-string-regexp@1.0.2
22 silly idealTree │ ├── glob@3.2.11
22 silly idealTree │ ├── minimatch@0.3.0
22 silly idealTree │ └── supports-color@1.2.0
22 silly idealTree ├── ms@0.7.1
22 silly idealTree ├── nan@2.6.2
22 silly idealTree ├── nopt@3.0.6
22 silly idealTree ├── oauth-sign@0.8.2
22 silly idealTree ├── once@1.4.0
22 silly idealTree ├─┬ optimist@0.6.1
22 silly idealTree │ ├── minimist@0.0.10
22 silly idealTree │ └── wordwrap@0.0.3
22 silly idealTree ├── optionator@0.8.2
22 silly idealTree ├── path-is-absolute@1.0.1
22 silly idealTree ├── pinkie-promise@2.0.1
22 silly idealTree ├── pinkie@2.0.4
22 silly idealTree ├── prelude-ls@1.1.2
22 silly idealTree ├── punycode@1.4.1
22 silly idealTree ├── qs@6.3.2
22 silly idealTree ├── repeat-string@1.6.1
22 silly idealTree ├── request@2.79.0
22 silly idealTree ├── resolve@1.1.7
22 silly idealTree ├── right-align@0.1.3
22 silly idealTree ├── should-equal@0.8.0
22 silly idealTree ├── should-format@0.3.2
22 silly idealTree ├── should-type@0.2.0
22 silly idealTree ├── should@8.4.0
22 silly idealTree ├── sigmund@1.0.1
22 silly idealTree ├── sntp@1.0.9
22 silly idealTree ├── source-map@0.2.0
22 silly idealTree ├── sprintf-js@1.0.3
22 silly idealTree ├─┬ sshpk@1.13.0
22 silly idealTree │ └── assert-plus@1.0.0
22 silly idealTree ├── stringstream@0.0.5
22 silly idealTree ├── strip-ansi@3.0.1
22 silly idealTree ├── supports-color@2.0.0
22 silly idealTree ├── to-iso-string@0.0.2
22 silly idealTree ├── tough-cookie@2.3.2
22 silly idealTree ├── tunnel-agent@0.4.3
22 silly idealTree ├── tweetnacl@0.14.5
22 silly idealTree ├── type-check@0.3.2
22 silly idealTree ├─┬ uglify-js@2.8.24
22 silly idealTree │ └── source-map@0.5.6
22 silly idealTree ├── uglify-to-browserify@1.0.2
22 silly idealTree ├── uuid@3.0.1
22 silly idealTree ├── verror@1.3.6
22 silly idealTree ├── which@1.2.14
22 silly idealTree ├── window-size@0.1.0
22 silly idealTree ├── wordwrap@1.0.0
22 silly idealTree ├── wrappy@1.0.2
22 silly idealTree ├── xtend@4.0.1
22 silly idealTree └── yargs@3.10.0
23 silly generateActionsToTake Starting
24 silly install generateActionsToTake
25 silly generateActionsToTake Finishing
26 silly diffTrees action count 0
27 silly decomposeActions action count 0
28 silly runTopLevelLifecycles Starting
29 silly install runPreinstallTopLevelLifecycles
30 silly preinstall lwip@0.0.9
31 info lifecycle lwip@0.0.9~preinstall: lwip@0.0.9
32 silly lifecycle lwip@0.0.9~preinstall: no script for preinstall, continuing
33 silly executeActions Starting
34 silly install executeActions
35 silly doSerial global-install 0
36 silly doParallel fetch 0
37 verbose correctMkdir /Users/birchbrowning/.npm/_locks correctMkdir not in flight; initializing
38 verbose lock using /Users/birchbrowning/.npm/_locks/staging-b6a1f823f7633dfd.lock for /Users/birchbrowning/GoogleDrive/Development/lwip/node_modules/.staging
39 silly doParallel extract 0
40 silly doParallel preinstall 0
41 silly doReverseSerial remove 0
42 silly doSerial move 0
43 silly doSerial finalize 0
44 silly doSerial build 0
45 silly doSerial global-link 0
46 silly doParallel update-linked 0
47 silly doSerial install 0
48 silly doSerial postinstall 0
49 verbose unlock done using /Users/birchbrowning/.npm/_locks/staging-b6a1f823f7633dfd.lock for /Users/birchbrowning/GoogleDrive/Development/lwip/node_modules/.staging
50 silly executeActions Finishing
51 silly rollbackFailedOptional Starting
52 silly rollbackFailedOptional Finishing
53 silly install runPostinstallTopLevelLifecycles
54 silly build lwip@0.0.9
55 info linkStuff lwip@0.0.9
56 silly linkStuff lwip@0.0.9 has /Users/birchbrowning/GoogleDrive/Development as its parent node_modules
57 verbose linkBins lwip@0.0.9
58 verbose linkMans lwip@0.0.9
59 silly install lwip@0.0.9
60 info lifecycle lwip@0.0.9~install: lwip@0.0.9
61 verbose lifecycle lwip@0.0.9~install: unsafe-perm in lifecycle true
62 verbose lifecycle lwip@0.0.9~install: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/birchbrowning/GoogleDrive/Development/lwip/node_modules/.bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/MacGPG2/bin:/Library/TeX/texbin
63 verbose lifecycle lwip@0.0.9~install: CWD: /Users/birchbrowning/GoogleDrive/Development/lwip
64 silly lifecycle lwip@0.0.9~install: Args: [ '-c', 'node-gyp rebuild' ]
65 silly lifecycle lwip@0.0.9~install: Returned: code: 1  signal: null
66 info lifecycle lwip@0.0.9~install: Failed to exec install script
67 verbose stack Error: lwip@0.0.9 install: `node-gyp rebuild`
67 verbose stack Exit status 1
67 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:279:16)
67 verbose stack     at emitTwo (events.js:106:13)
67 verbose stack     at EventEmitter.emit (events.js:191:7)
67 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
67 verbose stack     at emitTwo (events.js:106:13)
67 verbose stack     at ChildProcess.emit (events.js:191:7)
67 verbose stack     at maybeClose (internal/child_process.js:886:16)
67 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
68 verbose pkgid lwip@0.0.9
69 verbose cwd /Users/birchbrowning/GoogleDrive/Development/lwip
70 verbose Darwin 16.5.0
71 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
72 verbose node v6.10.3
73 verbose npm  v4.5.0
74 error code ELIFECYCLE
75 error errno 1
76 error lwip@0.0.9 install: `node-gyp rebuild`
76 error Exit status 1
77 error Failed at the lwip@0.0.9 install script 'node-gyp rebuild'.
77 error Make sure you have the latest version of node.js and npm installed.
77 error If you do, this is most likely a problem with the lwip package,
77 error not with npm itself.
77 error Tell the author that this fails on your system:
77 error     node-gyp rebuild
77 error You can get information on how to open an issue for this project with:
77 error     npm bugs lwip
77 error Or if that isn't available, you can get their info via:
77 error     npm owner ls lwip
77 error There is likely additional logging output above.
78 verbose exit [ 1, true ]
