### ISSUE TITLE
Failed to install on Redhat7

### ISSUE THREAD

**Issue by rochan** [EyalAr/lwip#305]
"protractor-screenshoter-plugin":"^0.3.2",
dependency chain image-to-ascii -> imgpx -> lwipify -> lwip2

LSB Version:	:core-4.1-amd64:core-4.1-noarch
Distributor ID:	RedHatEnterpriseServer
Description:	Red Hat Enterprise Linux Server release 7.2 (Maipo)
Release:	7.2
Codename:	Maipo

```
[INFO] [1/4] Resolving packages...
[INFO] [2/4] Fetching packages...
[INFO] [3/4] Linking dependencies...
[INFO] [4/4] Building fresh packages...
[INFO] info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
[ERROR] error /home/jenkins/workspace/<Dir>/tests/node_modules/lwip2: Command failed.
[ERROR] Exit code: 1
[ERROR] Command: sh
[ERROR] Arguments: -c node lib/install.js
[ERROR] Directory: /home/jenkins/workspace/<Dir>/tests/node_modules/lwip2
[ERROR] Output:
[ERROR] Installing lwip. If this fails, just install GraphicsMagick (http://www.graphicsmagick.org/).
[WARNING] npm WARN deprecated lodash-node@2.4.1: This package is discontinued. Use lodash@^4.0.0.
[ERROR] 
[ERROR] > lwip@0.0.9 install /home/jenkins/workspace/<Dir>/tests/node_modules/lwip2/node_modules/lwip
[ERROR] > node-gyp rebuild
[ERROR] 
[ERROR] make: Entering directory `/home/jenkins/workspace/<Dir>/tests/node_modules/lwip2/node_modules/lwip/build'
[ERROR]   CXX(target) Release/obj.target/lwip_decoder/src/decoder/init.o
[ERROR]   CXX(target) Release/obj.target/lwip_decoder/src/decoder/util.o
[ERROR]   CXX(target) Release/obj.target/lwip_decoder/src/decoder/buffer_worker.o
[ERROR] ../src/decoder/buffer_worker.cpp: In constructor ‘DecodeBufferWorker::DecodeBufferWorker(Nan::Callback*, v8::Local<v8::Object>&, buf_dec_f_t)’:
[ERROR] ../src/decoder/buffer_worker.cpp:8:58: warning: deprecated conversion from string constant to ‘char*’ [-Wwrite-strings]
[ERROR]      _height(0), _channels(0), _trans(false), _metadata("") {
[ERROR]                                                           ^
[ERROR]   CXX(target) Release/obj.target/lwip_decoder/src/decoder/jpeg_decoder.o
[ERROR]   CXX(target) Release/obj.target/lwip_decoder/src/decoder/png_decoder.o
[ERROR]   CXX(target) Release/obj.target/lwip_decoder/src/decoder/gif_decoder.o
[ERROR]   CC(target) Release/obj.target/lwip_decoder/src/lib/jpeg/jmemnobs.o
[ERROR]   CC(target) Release/obj.target/lwip_decoder/src/lib/jpeg/jcomapi.o
[ERROR]   CC(target) Release/obj.target/lwip_decoder/src/lib/jpeg/jdapimin.o
[ERROR]   CC(target) Release/obj.target/lwip_decoder/src/lib/jpeg/jdapistd.o
[ERROR]   CC(target) Release/obj.target/lwip_decoder/src/lib/jpeg/jdatadst.o
[ERROR]   CC(target) Release/obj.target/lwip_decoder/src/lib/jpeg/jdatasrc.o
[ERROR]   CC(target) Release/obj.target/lwip_decoder/src/lib/jpeg/jdcoefct.o
[ERROR]   CC(target) Release/obj.target/lwip_decoder/src/lib/jpeg/jdcolor.o
[ERROR]   CC(target) Release/obj.target/lwip_decoder/src/lib/jpeg/jddctmgr.o
[ERROR]   CC(target) Release/obj.target/lwip_decoder/src/lib/jpeg/jdhuff.o
[ERROR]   CC(target) Release/obj.target/lwip_decoder/src/lib/jpeg/jdinput.o
[ERROR]   CC(target) Release/obj.target/lwip_decoder/src/lib/jpeg/jdmainct.o
[ERROR]   CC(target) Release/obj.target/lwip_decoder/src/lib/jpeg/jdmarker.o
[ERROR]   CC(target) Release/obj.target/lwip_decoder/src/lib/jpeg/jdmaster.o
[ERROR]   CC(target) Release/obj.target/lwip_decoder/src/lib/jpeg/jdpostct.o
[ERROR]   CC(target) Release/obj.target/lwip_decoder/src/lib/jpeg/jdsample.o
[ERROR]   CC(target) Release/obj.target/lwip_decoder/src/lib/jpeg/jerror.o
[ERROR]   CC(target) Release/obj.target/lwip_decoder/src/lib/jpeg/jfdctflt.o
[ERROR]   CC(target) Release/obj.target/lwip_decoder/src/lib/jpeg/jfdctfst.o
[ERROR]   CC(target) Release/obj.target/lwip_decoder/src/lib/jpeg/jfdctint.o
[ERROR]   CC(target) Release/obj.target/lwip_decoder/src/lib/jpeg/jidctflt.o
[ERROR]   CC(target) Release/obj.target/lwip_decoder/src/lib/jpeg/jidctfst.o
[ERROR]   CC(target) Release/obj.target/lwip_decoder/src/lib/jpeg/jidctint.o
[ERROR]   CC(target) Release/obj.target/lwip_decoder/src/lib/jpeg/jutils.o
[ERROR]   CC(target) Release/obj.target/lwip_decoder/src/lib/jpeg/jmemmgr.o
[ERROR]   CC(target) Release/obj.target/lwip_decoder/src/lib/jpeg/jdarith.o
[ERROR]   CC(target) Release/obj.target/lwip_decoder/src/lib/jpeg/jdmerge.o
[ERROR]   CC(target) Release/obj.target/lwip_decoder/src/lib/jpeg/jaricom.o
[ERROR]   CC(target) Release/obj.target/lwip_decoder/src/lib/jpeg/jquant1.o
[ERROR]   CC(target) Release/obj.target/lwip_decoder/src/lib/jpeg/jquant2.o
[ERROR]   CC(target) Release/obj.target/lwip_decoder/src/lib/png/png.o
[ERROR] In file included from ../src/lib/png/png.c:14:0:
[ERROR] ../src/lib/png/pngpriv.h:805:4: error: #error ZLIB_VERNUM != PNG_ZLIB_VERNUM "-I (include path) error: see the notes in pngpriv.h"
[ERROR]  #  error ZLIB_VERNUM != PNG_ZLIB_VERNUM \
[ERROR]     ^
[ERROR] make: *** [Release/obj.target/lwip_decoder/src/lib/png/png.o] Error 1
[ERROR] make: Leaving directory `/home/jenkins/workspace/<Dir>/tests/node_modules/lwip2/node_modules/lwip/build'
[ERROR] gyp ERR! build error 
[ERROR] gyp ERR! stack Error: `make` failed with exit code: 2
[ERROR] gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
[ERROR] gyp ERR! stack     at emitTwo (events.js:87:13)
[ERROR] gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
[ERROR] gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:12)
[ERROR] gyp ERR! System Linux 3.10.0-327.10.1.el7.x86_64
[ERROR] gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
[ERROR] gyp ERR! cwd /home/jenkins/workspace/<Dir>/tests/node_modules/lwip2/node_modules/lwip
[ERROR] gyp ERR! node -v v4.8.3
[ERROR] gyp ERR! node-gyp -v v3.4.0
[ERROR] gyp ERR! not ok 
[ERROR] npm ERR! Linux 3.10.0-327.10.1.el7.x86_64
[ERROR] npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "i" "lwip@0.0.9"
[ERROR] npm ERR! node v4.8.3
[ERROR] npm ERR! npm  v2.15.11
[ERROR] npm ERR! code ELIFECYCLE
[ERROR] 
[ERROR] npm ERR! lwip@0.0.9 install: `node-gyp rebuild`
[ERROR] npm ERR! Exit status 1
[ERROR] npm ERR! 
[ERROR] npm ERR! Failed at the lwip@0.0.9 install script 'node-gyp rebuild'.
[ERROR] npm ERR! This is most likely a problem with the lwip package,
[ERROR] npm ERR! not with npm itself.
[ERROR] npm ERR! Tell the author that this fails on your system:
[ERROR] npm ERR!     node-gyp rebuild
[ERROR] npm ERR! You can get information on how to open an issue for this project with:
[ERROR] npm ERR!     npm bugs lwip
[ERROR] npm ERR! Or if that isn't available, you can get their info via:
[ERROR] npm ERR! 
[ERROR] npm ERR!     npm owner ls lwip
[ERROR] npm ERR! There is likely additional logging output above.
[ERROR] 
[ERROR] npm ERR! Please include the following file with any support request:
[ERROR] npm ERR!     /home/jenkins/workspace/<Dir>/tests/node_modules/lwip2/npm-debug.log
[ERROR] It seems like lwip failed to be intalled. Please check the errors.
```

**Comment by rochan** [comment]
Closing this issue, found a work around to install graphicsmagick locally through yum install
