### ISSUE TITLE
LWIP installation error

### ISSUE THREAD

**Issue by vinci58123** [EyalAr/lwip#314]
Hi, unsure of how to get this working, installed using cmd have node.js installed v 8.9.1, 

unsure of what the log says:

gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Windows_NT 10.0.16299
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\CheangK\node_modules\lwip
gyp ERR! node -v v8.9.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\CheangK\package.json'
npm WARN CheangK No description
npm WARN CheangK No repository field.
npm WARN CheangK No README data
npm WARN CheangK No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! lwip@0.0.9 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the lwip@0.0.9 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\CheangK\AppData\Roaming\npm-cache\_logs\2017-12-05T02_34_28_429Z-debug.log

**Comment by vinci58123** [comment]
Tried Cloning and installing too using cd lwip && npm install but the log says system cannot find the path specified

**Comment by tom-james-watson** [comment]
This project seems to be dead. Try this version - https://github.com/Pajk/lwip

**Comment by vinci58123** [comment]
hey thanks for the reply!! i'll check it out

**Comment by mbret** [comment]
@tom-james-watson the project you linked seems as dead as this one

**Comment by gyfeng1003** [comment]
+1

**Comment by selfrefactor** [comment]
I use `lwip` with `Node 6.2.0`. Newer versions than this shouldn't work.
