### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by shekar-raja** [EyalAr/lwip#318]
npm WARN deprecated lodash-node@2.4.1: This package is discontinued. Use lodash@^4.0.0.

> lwip@0.0.9 install C:\Users\rajasekhar.b\node_modules\lwip
> node-gyp rebuild

C:\Users\rajasekhar.b\node_modules\lwip>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:484:19)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:509:16)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:154:21)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\rajasekhar.b\node_modules\lwip
gyp ERR! node -v v10.12.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\rajasekhar.b\package.json'
npm WARN rajasekhar.b No description
npm WARN rajasekhar.b No repository field.
npm WARN rajasekhar.b No README data
npm WARN rajasekhar.b No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! lwip@0.0.9 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the lwip@0.0.9 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\rajasekhar.b\AppData\Roaming\npm-cache\_logs\2018-10-23T06_33_04_759Z-debug.log

**Comment by roganoalien** [comment]
same here, cannot be used now. Is there a fix?

**Comment by 8secz-johndpope** [comment]
see my last comment https://github.com/EyalAr/lwip/issues/306

**Comment by krishnadevz** [comment]
Note: Installation of this module involves compiling native code. If npm install lwip failes, you probably need to setup your system. See instructions(https://github.com/nodejs/node-gyp#installation). Building on Windows with Visual Studio requires version 2013 or higher.
or <b>newer versions of node not supporting `this` package</b>
