### ISSUE TITLE
Failed install

### ISSUE THREAD

**Issue by cscrum** [EyalAr/lwip#322]
Trying to install on Ubuntu 14.04
npm install lwip
npm WARN deprecated lodash-node@2.4.1: This package is discontinued. Use lodash@^4.0.0.

> lwip@0.0.9 install /var/www/neonetworks/node_modules/lwip
> node-gyp rebuild

make: Entering directory `/var/www/neonetworks/node_modules/lwip/build'
  CXX(target) Release/obj.target/lwip_decoder/src/decoder/init.o
In file included from ../src/decoder/init.cpp:1:0:
../src/decoder/decoder.h:91:14: error: variable or field ‘initAll’ declared void
 void initAll(Handle<Object> exports);
              ^
../src/decoder/decoder.h:91:14: error: ‘Handle’ was not declared in this scope
../src/decoder/decoder.h:91:27: error: expected primary-expression before ‘>’ token
 void initAll(Handle<Object> exports);
                           ^
../src/decoder/decoder.h:91:29: error: ‘exports’ was not declared in this scope
 void initAll(Handle<Object> exports);
                             ^
make: *** [Release/obj.target/lwip_decoder/src/decoder/init.o] Error 1
make: Leaving directory `/var/www/neonetworks/node_modules/lwip/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:321:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Linux 5.3.11-x86_64-linode131
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /var/www/neonetworks/node_modules/lwip
gyp ERR! node -v v12.16.0
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.2 (node_modules/mocha/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.11 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.11: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! lwip@0.0.9 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the lwip@0.0.9 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-02-14T18_23_07_637Z-debug.log

**Comment by cscrum** [comment]
So I downloaded the repo and ran npm install locally, but now when trying to launch my app I get:
 node server.js
/var/www/neonetworks/node_modules/lwip/node_modules/bindings/bindings.js:135
  throw err;
  ^

Error: Could not locate the bindings file. Tried:
 → /var/www/neonetworks/node_modules/lwip/build/lwip_image.node
 → /var/www/neonetworks/node_modules/lwip/build/Debug/lwip_image.node
 → /var/www/neonetworks/node_modules/lwip/build/Release/lwip_image.node
 → /var/www/neonetworks/node_modules/lwip/out/Debug/lwip_image.node
 → /var/www/neonetworks/node_modules/lwip/Debug/lwip_image.node
 → /var/www/neonetworks/node_modules/lwip/out/Release/lwip_image.node
 → /var/www/neonetworks/node_modules/lwip/Release/lwip_image.node
 → /var/www/neonetworks/node_modules/lwip/build/default/lwip_image.node
 → /var/www/neonetworks/node_modules/lwip/compiled/13.8.0/linux/x64/lwip_image.node
 → /var/www/neonetworks/node_modules/lwip/addon-build/release/install-root/lwip_image.node
 → /var/www/neonetworks/node_modules/lwip/addon-build/debug/install-root/lwip_image.node
 → /var/www/neonetworks/node_modules/lwip/addon-build/default/install-root/lwip_image.node
 → /var/www/neonetworks/node_modules/lwip/lib/binding/node-v79-linux-x64/lwip_image.node
    at bindings (/var/www/neonetworks/node_modules/lwip/node_modules/bindings/bindings.js:126:9)
    at /var/www/neonetworks/node_modules/lwip/lib/Image.js:3:41
    at Object.<anonymous> (/var/www/neonetworks/node_modules/lwip/lib/Image.js:16:3)
    at Module._compile (internal/modules/cjs/loader.js:1151:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1171:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Module.require (internal/modules/cjs/loader.js:1040:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at /var/www/neonetworks/node_modules/lwip/lib/ImagePrototypeInit.js:3:17 {
  tries: [
    '/var/www/neonetworks/node_modules/lwip/build/lwip_image.node',
    '/var/www/neonetworks/node_modules/lwip/build/Debug/lwip_image.node',
    '/var/www/neonetworks/node_modules/lwip/build/Release/lwip_image.node',
    '/var/www/neonetworks/node_modules/lwip/out/Debug/lwip_image.node',
    '/var/www/neonetworks/node_modules/lwip/Debug/lwip_image.node',
    '/var/www/neonetworks/node_modules/lwip/out/Release/lwip_image.node',
    '/var/www/neonetworks/node_modules/lwip/Release/lwip_image.node',
    '/var/www/neonetworks/node_modules/lwip/build/default/lwip_image.node',
    '/var/www/neonetworks/node_modules/lwip/compiled/13.8.0/linux/x64/lwip_image.node',
    '/var/www/neonetworks/node_modules/lwip/addon-build/release/install-root/lwip_image.node',
    '/var/www/neonetworks/node_modules/lwip/addon-build/debug/install-root/lwip_image.node',
    '/var/www/neonetworks/node_modules/lwip/addon-build/default/install-root/lwip_image.node',
    '/var/www/neonetworks/node_modules/lwip/lib/binding/node-v79-linux-x64/lwip_image.node'
  ]
}
Not real sure what this means. Any help?

**Comment by hzsydy** [comment]
Same here, on macOS 10.15.4.

**Comment by Pecacheu** [comment]
I'm getting the same error as OP on WSL Ubuntu 20.04. Latest node v16.13.0

```
-- Cut out C++ warnings --
npm ERR! In file included from ../src/decoder/init.cpp:1:
npm ERR! ../src/decoder/decoder.h: At global scope:
npm ERR! ../src/decoder/decoder.h:91:14: error: variable or field ‘initAll’ declared void
npm ERR!    91 | void initAll(Handle<Object> exports);
npm ERR!       |              ^~~~~~
npm ERR! ../src/decoder/decoder.h:91:14: error: ‘Handle’ was not declared in this scope
npm ERR! ../src/decoder/decoder.h:91:27: error: expected primary-expression before ‘>’ token
npm ERR!    91 | void initAll(Handle<Object> exports);
npm ERR!       |                           ^
npm ERR! ../src/decoder/decoder.h:91:29: error: ‘exports’ was not declared in this scope
npm ERR!    91 | void initAll(Handle<Object> exports);
npm ERR!       |                             ^~~~~~~
npm ERR! gyp ERR! build error
npm ERR! gyp ERR! stack Error: `make` failed with exit code: 2
npm ERR! gyp ERR! stack     at ChildProcess.onExit (/snap/node/5534/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:390:28)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
npm ERR! gyp ERR! System Linux 4.19.128-microsoft-standard
npm ERR! gyp ERR! command "/snap/node/5534/bin/node" "/snap/node/5534/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
npm ERR! gyp ERR! cwd /mnt/c/Users/Pecac/Desktop/DigiBoard/node_modules/lwip
npm ERR! gyp ERR! node -v v16.13.0
npm ERR! gyp ERR! node-gyp -v v8.2.0
npm ERR! gyp ERR! not ok
```
