### ISSUE TITLE
Problem during install on node-webkit

### ISSUE THREAD

**Issue by yoyoy** [EyalAr/lwip#53]
Hi, I try to install this package i a node webkit project

so i user this command line (i'm on windows 8 64)
c:\wamp\www\xxx\application\app>npm install lwip  --save

and i get this result

npm WARN package.json xxx@ No description
npm WARN package.json xxx@ No repository field.
## npm WARN package.json xxx@ No README data

> lwip@0.0.4 install c:\wamp\www\xxx\application\app\node_modules\lwip
> node-gyp rebuild

c:\wamp\www\xxx\application\app\node_modules\lwip>node "C:\Program Files\no
dejs\node_modules\npm\bin\node-gyp-bin\....\node_modules\node-gyp\bin\node-gyp
.js" rebuild
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYT
HON env variable.
gyp ERR! stack     at failNoPython (C:\Program Files\nodejs\node_modules\npm\nod
e_modules\node-gyp\lib\configure.js:103:14)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node
-gyp\lib\configure.js:64:11
gyp ERR! stack     at Object.oncomplete (evalmachine.<anonymous>:107:15)
gyp ERR! System Windows_NT 6.2.9200
gyp ERR! command "node" "C:\Program Files\nodejs\node_modules\npm\node_modu
les\node-gyp\bin\node-gyp.js" "rebuild"
gyp ERR! cwd c:\wamp\www\xxx\application\app\node_modules\lwip
gyp ERR! node -v v0.10.31
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok
npm ERR! lwip@0.0.4 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the lwip@0.0.4 install script.
npm ERR! This is most likely a problem with the lwip package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls lwip
npm ERR! There is likely additional logging output above.

npm ERR! System Windows_NT 6.2.9200
npm ERR! command "C:\Program Files\nodejs\\node.exe" "C:\Program Files\nod
ejs\node_modules\npm\bin\npm-cli.js" "install" "lwip" "--save"
npm ERR! cwd c:\wamp\www\xxx\application\app
npm ERR! node -v v0.10.31
npm ERR! npm -v 1.4.23
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     c:\wamp\www\xxx\application\app\npm-debug.log
npm ERR! not ok code 0

do you have an idea ? 
thanks

**Comment by yoyoy** [comment]
hello
i'm sorry but i'm a little lost ...
could you help me for installation ? 
I have this message :'(
```shell
Your environment has been set up for using Node.js 0.10.31 (x64) and npm.

C:\Users\N>npm install -g nw-gyp
C:\Users\N\AppData\Roaming\npm\nw-gyp -> C:\Users\N\AppData\Roaming\npm\node_mod
ules\nw-gyp\bin\nw-gyp.js
nw-gyp@0.12.4 C:\Users\N\AppData\Roaming\npm\node_modules\nw-gyp
├── which@1.0.8
├── osenv@0.1.0
├── graceful-fs@2.0.3
├── rimraf@2.2.8
├── semver@2.2.1
├── nopt@2.2.1 (abbrev@1.0.5)
├── minimatch@0.4.0 (sigmund@1.0.0, lru-cache@2.5.0)
├── mkdirp@0.5.0 (minimist@0.0.8)
├── fstream@0.1.31 (inherits@2.0.1, graceful-fs@3.0.5)
├── tar@0.1.20 (inherits@2.0.1, block-stream@0.0.7)
├── glob@3.2.11 (inherits@2.0.1, minimatch@0.3.0)
├── npmlog@0.1.1 (ansi@0.3.0)
└── request@2.51.0 (caseless@0.8.0, json-stringify-safe@5.0.0, aws-sign2@0.5.0,
forever-agent@0.5.2, oauth-sign@0.5.0, tunnel-agent@0.4.0, stringstream@0.0.4, q
s@2.3.3, node-uuid@1.4.2, mime-types@1.0.2, tough-cookie@0.12.1, combined-stream
@0.0.7, http-signature@0.10.1, form-data@0.2.0, hawk@1.1.1, bl@0.9.3)

C:\Users\N>nw-gyp configure --target=0.10.31
gyp info it worked if it ends with ok
gyp info using nw-gyp@0.12.4
gyp info using node@0.10.31 | win32 | x64
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYT
HON env variable.
gyp ERR! stack     at failNoPython (C:\Users\N\AppData\Roaming\npm\node_modules\
nw-gyp\lib\configure.js:101:14)
gyp ERR! stack     at C:\Users\N\AppData\Roaming\npm\node_modules\nw-gyp\lib\con
figure.js:64:11
gyp ERR! stack     at Object.oncomplete (fs.js:107:15)
gyp ERR! System Windows_NT 6.2.9200
gyp ERR! command "node" "C:\\Users\\N\\AppData\\Roaming\\npm\\node_modules\\nw-g
yp\\bin\\nw-gyp.js" "configure" "--target=0.10.31"
gyp ERR! cwd C:\Users\N
gyp ERR! node -v v0.10.31
gyp ERR! nw-gyp -v v0.12.4
gyp ERR! not ok

C:\Users\N>
```

thanks

**Comment by yoyoy** [comment]
again ...
i've istaller python 27 and now there is a 404 error :'(

```shell

C:\Users\N>nw-gyp configure --target=0.10.31 --python C:\Python27\python.exe
gyp info it worked if it ends with ok
gyp info using nw-gyp@0.12.4
gyp info using node@0.10.31 | win32 | x64
gyp http GET http://node-webkit.s3.amazonaws.com/v0.10.31/nw-headers-v0.10.31.ta
r.gz
gyp http 404 http://node-webkit.s3.amazonaws.com/v0.10.31/nw-headers-v0.10.31.ta
r.gz
gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: 404 status code downloading tarball
gyp ERR! stack     at Request.<anonymous> (C:\Users\N\AppData\Roaming\npm\node_m
odules\nw-gyp\lib\install.js:234:14)
gyp ERR! stack     at Request.emit (events.js:117:20)
gyp ERR! stack     at Request.onRequestResponse (C:\Users\N\AppData\Roaming\npm\
node_modules\nw-gyp\node_modules\request\request.js:1255:10)
gyp ERR! stack     at ClientRequest.emit (events.js:95:17)
gyp ERR! stack     at HTTPParser.parserOnIncomingClient (http.js:1688:21)
gyp ERR! stack     at HTTPParser.parserOnHeadersComplete [as onHeadersComplete]
(http.js:121:23)
gyp ERR! stack     at Socket.socketOnData (http.js:1583:20)
gyp ERR! stack     at TCP.onread (net.js:527:27)
gyp ERR! System Windows_NT 6.2.9200
gyp ERR! command "node" "C:\\Users\\N\\AppData\\Roaming\\npm\\node_modules\\nw-g
yp\\bin\\nw-gyp.js" "configure" "--target=0.10.31" "--python" "C:\\Python27\\pyt
hon.exe"
gyp ERR! cwd C:\Users\N
gyp ERR! node -v v0.10.31
gyp ERR! nw-gyp -v v0.12.4
gyp ERR! not ok
```

help :'(

**Comment by yoyoy** [comment]
me again ...
so i've installed python 27
started node comand prompt as administrator to avoid problem working in program files folder ...
used a config for 0.10.3 (and not 31) to avoid 404 error on amazon links ...

and now i'm lost :'(

```shell
Your environment has been set up for using Node.js 0.10.31 (x64) and npm.

C:\Windows\System32>cd "c:\Program Files\nodejs\node_modules"

c:\Program Files\nodejs\node_modules>nw-gyp configure --target=0.10.3 --python c
:\Python27\python.exe
gyp info it worked if it ends with ok
gyp info using nw-gyp@0.12.4
gyp info using node@0.10.31 | win32 | x64
gyp info spawn c:\Python27\python.exe
gyp info spawn args [ 'C:\\Users\\N\\AppData\\Roaming\\npm\\node_modules\\nw-gyp
\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=auto',
gyp info spawn args   '-I',
gyp info spawn args   'c:\\Program Files\\nodejs\\node_modules\\build\\config.gy
pi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\N\\AppData\\Roaming\\npm\\node_modules\\nw-gyp
\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\N\\.nw-gyp\\0.10.3\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\N\\.nw-gyp\\0.10.3',
gyp info spawn args   '-Dmodule_root_dir=c:\\Program Files\\nodejs\\node_modules
',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--generator-output',
gyp info spawn args   'c:\\Program Files\\nodejs\\node_modules\\build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp: binding.gyp not found (cwd: c:\Program Files\nodejs\node_modules)
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Users\N\AppData\Roaming\npm\node
_modules\nw-gyp\lib\configure.js:353:16)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:810:
12)
gyp ERR! System Windows_NT 6.2.9200
gyp ERR! command "node" "C:\\Users\\N\\AppData\\Roaming\\npm\\node_modules\\nw-g
yp\\bin\\nw-gyp.js" "configure" "--target=0.10.3" "--python" "c:\\Python27\\pyth
on.exe"
gyp ERR! cwd c:\Program Files\nodejs\node_modules
gyp ERR! node -v v0.10.31
gyp ERR! nw-gyp -v v0.12.4
gyp ERR! not ok

c:\Program Files\nodejs\node_modules>
```

thanks for your support if any ;)

**Comment by EyalAr** [comment]
You are not in the correct dir.
You did `cd "c:\Program Files\nodejs\node_modules"`
But it should be `cd "c:\Program Files\nodejs\node_modules\lwip"`

Try again and let me know.
